"""Method package — re-exports the public API.

Generated by `scripts/finalize_package_init.py` after the Stage 2 producer agents
complete. The `__all__` list below is ordered per the taxonomy build plan's
`package_manifest.files[__init__.py].content_rule`:
  [pluggable_component.name, *method_helpers, *architecture_classes,
   *training_functions, load_data].
"""

from .data import load_data
from .method import (
    compute_gradient_embeddings,
    kmeans_plus_plus_seeding,
    select_batch,
)
from .model import GradientEmbeddingMLP
from .training import build_model, train_from_scratch

__all__ = [
    "select_batch",
    "compute_gradient_embeddings",
    "kmeans_plus_plus_seeding",
    "GradientEmbeddingMLP",
    "build_model",
    "train_from_scratch",
    "load_data",
]
