"""Method package — re-exports the public API.

Generated by `scripts/finalize_package_init.py` after the Stage 2 producer agents
complete. The `__all__` list below is ordered per the paradigm field guide's
`package_manifest.files[__init__.py].content_rule`:
  [pluggable_component.name, *method_helpers, *architecture_classes,
   *training_functions, load_data].
"""

from .data import load_environment, load_problem
from .method import (
    compute_j_clearance,
    compute_j_count_obs,
    compute_j_distance,
    compute_j_future_obs,
    compute_j_heading,
    compute_j_risk_obs,
    plan,
    predict_obstacle_position,
)
from .model import UnicycleDynamics, CollisionModel
from .training import precompute_motion_primitives

__all__ = [
    "plan",
    "compute_j_clearance",
    "compute_j_count_obs",
    "compute_j_distance",
    "compute_j_future_obs",
    "compute_j_heading",
    "compute_j_risk_obs",
    "predict_obstacle_position",
    "UnicycleDynamics",
    "CollisionModel",
    "precompute_motion_primitives",
    "load_environment",
    "load_problem",
]
