"""Method package — re-exports the public API.

Generated by `scripts/finalize_package_init.py` after the Stage 2 producer agents
complete. The `__all__` list below is ordered per the taxonomy build plan's
`package_manifest.files[__init__.py].content_rule`:
  [pluggable_component.name, *method_helpers, *architecture_classes,
   *training_functions, load_data].
"""

from .data import load_source_detectors, load_target_data
from .method import (
    detector_weighing,
    filter_pseudo_labels,
    generate_pseudo_labels,
    kalman_track,
    kbf_fuse_boxes,
    refine_pedestrians,
    refine_static_vehicles,
    retroactive_labeling,
    run_ensemble_detections,
)
from .model import LiDAR3DDetector
from .training import build_detector, retrain_on_pseudo_labels

__all__ = [
    "generate_pseudo_labels",
    "detector_weighing",
    "filter_pseudo_labels",
    "kalman_track",
    "kbf_fuse_boxes",
    "refine_pedestrians",
    "refine_static_vehicles",
    "retroactive_labeling",
    "run_ensemble_detections",
    "LiDAR3DDetector",
    "build_detector",
    "retrain_on_pseudo_labels",
    "load_target_data",
    "load_source_detectors",
]
