#!/usr/bin/env python3
"""Generated role-view documentation from the taxonomy SSOT."""

from __future__ import annotations

from copy import deepcopy
from pathlib import Path
from typing import Any

import yaml

from scripts import taxonomy
from scripts.build_plan import load_build_plan


ROOT = Path(__file__).resolve().parent.parent
ROLE_OUTPUT_ROOT = Path("docs/generated/field-guides")
ROLE_VIEW_MARKER = "<!-- Generated by scripts/refresh_ssot_docs.py taxonomy role views. -->"
LEGACY_ROLE_VIEW_MARKER = "<!-- Generated by scripts/validate_field_guides.py role views. -->"
ROLES = ("analyzer", "producer", "reviewer", "notebook", "diagnostician")


def render_role_views(
    repo_root: Path = ROOT,
    output_root: Path = ROLE_OUTPUT_ROOT,
) -> dict[Path, str]:
    """Render one role-view file per taxonomy-served legacy paradigm and role."""

    tax = taxonomy.load_taxonomy(repo_root)
    rendered: dict[Path, str] = {}
    for paradigm_id in sorted(tax._node_by_legacy):
        node = taxonomy.serves(paradigm_id, tax)
        if node is None:
            continue
        pack = taxonomy.load_pack(paradigm_id, repo_root)
        if pack is None:
            continue
        plan = load_build_plan(_build_doc_spec(paradigm_id, pack), repo_root)
        for role in ROLES:
            rel_path = output_root / paradigm_id / f"{role}.md"
            rendered[rel_path] = render_role_view(
                tax=tax,
                node=node,
                paradigm_id=paradigm_id,
                pack=pack,
                build_plan=plan,
                role=role,
            )
    return rendered


def render_role_view(
    *,
    tax: taxonomy.Taxonomy,
    node: taxonomy.VariantNode | taxonomy.FamilyNode,
    paradigm_id: str,
    pack: dict[str, Any],
    build_plan: dict[str, Any] | None,
    role: str,
) -> str:
    if role not in ROLES:
        raise ValueError(f"unknown taxonomy role-view role: {role}")
    lines: list[str] = [
        ROLE_VIEW_MARKER,
        f"# {paradigm_id} - {role} view",
        "",
        f"Source taxonomy node: `{pack['taxonomy_id']}`",
        f"Legacy paradigm id: `{paradigm_id}`",
        "Inheritance chain: " + " -> ".join(_chain_labels(tax, node)),
        "",
        (
            "This generated view is maintainer documentation rendered from "
            "`docs/ssot/taxonomies.yaml`; runtime consumers should use "
            "`scripts.taxonomy` and `scripts.build_plan`."
        ),
        "",
    ]
    _append_blocks(lines, _blocks_for_role(role, pack, build_plan))
    return "\n".join(lines).rstrip() + "\n"


def write_role_views(
    rendered: dict[Path, str],
    repo_root: Path = ROOT,
    output_root: Path = ROLE_OUTPUT_ROOT,
) -> int:
    root = repo_root / output_root
    root.mkdir(parents=True, exist_ok=True)
    stale = _generated_role_files(root)
    expected = {repo_root / rel for rel in rendered}
    for path in sorted(stale - expected):
        path.unlink()
    written = 0
    for rel_path, text in sorted(rendered.items(), key=lambda item: item[0].as_posix()):
        path = repo_root / rel_path
        path.parent.mkdir(parents=True, exist_ok=True)
        old = path.read_text(encoding="utf-8") if path.is_file() else None
        if old != text:
            path.write_text(text, encoding="utf-8")
            written += 1
    return written


def generated_role_files(root: Path) -> set[Path]:
    return _generated_role_files(root)


def _build_doc_spec(paradigm_id: str, pack: dict[str, Any]) -> dict[str, Any]:
    pluggable = deepcopy(pack.get("pluggable_component") or {})
    contract = pluggable.get("contract") if isinstance(pluggable.get("contract"), dict) else {}
    return {
        "comparison": {
            "classification": {"id": paradigm_id},
            "pluggable_component": {
                "name": pluggable.get("name"),
                "signature": pluggable.get("signature_template"),
                "seed_param": contract.get("seed_param") or "seed",
            },
        },
        "critical_requirements": {
            "model": {"specific_features": []},
            "required_model_methods": [],
        },
    }


def _blocks_for_role(
    role: str,
    pack: dict[str, Any],
    build_plan: dict[str, Any] | None,
) -> list[tuple[str, Any]]:
    plan_blocks = _build_plan_blocks(build_plan)
    if role == "analyzer":
        return [
            ("fingerprint", pack.get("fingerprint")),
            ("priors", pack.get("priors")),
            ("scaffold_hints", pack.get("scaffold_hints")),
            ("pluggable_component", pack.get("pluggable_component")),
            ("smoke_economics", pack.get("smoke_economics")),
            ("paradigm_extras", pack.get("paradigm_extras")),
            ("model_defaults", pack.get("model_defaults")),
            ("domain_checks", pack.get("domain_checks")),
        ]
    if role == "producer":
        return [
            ("pluggable_component", pack.get("pluggable_component")),
            ("scaffold_hints", pack.get("scaffold_hints")),
            *plan_blocks,
            ("notebook_layout", pack.get("notebook_layout")),
            ("demo_skill", pack.get("demo_skill")),
        ]
    if role == "reviewer":
        return [
            ("semantic_checks", pack.get("semantic_checks")),
            ("pluggable_component", pack.get("pluggable_component")),
            *plan_blocks,
            ("notebook_layout", pack.get("notebook_layout")),
            ("demo_skill", pack.get("demo_skill")),
        ]
    if role == "notebook":
        return [
            ("pluggable_component", pack.get("pluggable_component")),
            ("notebook_layout", pack.get("notebook_layout")),
            ("demo_skill", pack.get("demo_skill")),
            ("smoke_economics", pack.get("smoke_economics")),
            ("smoke_bugs", pack.get("smoke_bugs")),
        ]
    return [
        ("smoke_bugs", pack.get("smoke_bugs")),
        ("semantic_checks", pack.get("semantic_checks")),
        ("pluggable_component", pack.get("pluggable_component")),
        ("demo_skill", pack.get("demo_skill")),
        *plan_blocks,
    ]


def _build_plan_blocks(build_plan: dict[str, Any] | None) -> list[tuple[str, Any]]:
    if not build_plan:
        return []
    return [
        (
            "build_plan",
            {
                "schema_version": build_plan.get("schema_version"),
                "source": build_plan.get("source"),
                "interface_hint": build_plan.get("interface_hint"),
            },
        ),
        ("package_manifest", build_plan.get("package_manifest")),
        ("arch_contract_requirements", build_plan.get("arch_contract_requirements")),
    ]


def _chain_labels(
    tax: taxonomy.Taxonomy,
    node: taxonomy.VariantNode | taxonomy.FamilyNode,
) -> list[str]:
    if isinstance(node, taxonomy.FamilyNode):
        return [node.legacy_paradigm or node.id]
    family = tax.roots[node.root_id].families[node.family_id]
    by_slug: dict[str, taxonomy.VariantNode] = {}

    def index(variant: taxonomy.VariantNode) -> None:
        by_slug[variant.slug] = variant
        for child in variant.sub_variants.values():
            index(child)

    for variant in family.variants.values():
        index(variant)
    chain: list[taxonomy.VariantNode] = []
    current: taxonomy.VariantNode | None = node
    while current is not None:
        chain.append(current)
        current = by_slug.get(current.parent_slug) if current.parent_slug else None
    return [item.legacy_paradigm or item.slug for item in reversed(chain)]


def _append_blocks(lines: list[str], blocks: list[tuple[str, Any]]) -> None:
    appended = False
    for title, value in blocks:
        if value in ({}, [], None):
            continue
        appended = True
        lines.extend(
            [
                f"## {title}",
                "",
                "```yaml",
                _yaml(value).rstrip(),
                "```",
                "",
            ]
        )
    if not appended:
        lines.extend(["_No taxonomy-owned blocks for this role._", ""])


def _yaml(value: Any) -> str:
    return yaml.safe_dump(value, sort_keys=False, allow_unicode=False)


def _generated_role_files(root: Path) -> set[Path]:
    if not root.exists():
        return set()
    files: set[Path] = set()
    for path in root.rglob("*.md"):
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        if text.startswith(ROLE_VIEW_MARKER) or text.startswith(LEGACY_ROLE_VIEW_MARKER):
            files.add(path)
    return files
