"""Closed deterministic offline data generator for time-series forecasting.

R2C-052's third acquisition tier is family-owned.  It accepts only the
resolved time_series_panel_v1 build-plan contract and one typed single-holdout
protocol. Unsupported inputs return a typed refusal and publish no files.
"""

from __future__ import annotations

import csv
import hashlib
import io
import json
import math
import os
import tempfile
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Literal


SCHEMA_ID = "time_series_panel_v1"
PROVENANCE_SCHEMA_VERSION = "1.0.0"
GENERATOR_ID = "time_series_offline_fallback"
GENERATOR_VERSION = "1.0.0"
SYNTHETIC_TIER = "family_owned_synthetic"
SERIES_FILENAME = "series.csv"
OBSERVATIONS_FILENAME = "observations.csv"
PROVENANCE_FILENAME = "PROVENANCE.json"
TRANSACTION_FILENAME = ".R2C_OFFLINE_FALLBACK_TRANSACTION.json"
PUBLISHED_FILENAMES = (
    SERIES_FILENAME, OBSERVATIONS_FILENAME, PROVENANCE_FILENAME,
)

SUPPORTED_FAMILY_IDS = frozenset({
    "time_series_forecasting", "graph_time_series_forecasting",
})
SUPPORTED_CADENCES = ("week", "day", "hour", "minute", "second")
PROTOCOL_ROLES = (
    "context_length", "forecast_call_horizon", "validation_span", "test_span",
)
SERIES_COLUMNS = (
    {"name": "series_id", "dtype": "string", "semantic_role": "entity_id"},
    {
        "name": "static_level", "dtype": "float64",
        "semantic_role": "static_numeric_level",
    },
    {
        "name": "static_amplitude", "dtype": "float64",
        "semantic_role": "static_numeric_amplitude",
    },
)
OBSERVATION_COLUMNS = (
    {"name": "series_id", "dtype": "string", "semantic_role": "entity_id"},
    {
        "name": "timestamp", "dtype": "datetime_iso8601_utc",
        "semantic_role": "time_index",
    },
    {"name": "target", "dtype": "float64", "semantic_role": "target"},
    {
        "name": "season_sin", "dtype": "float64",
        "semantic_role": "known_time_varying_covariate",
    },
    {
        "name": "season_cos", "dtype": "float64",
        "semantic_role": "known_time_varying_covariate",
    },
    {
        "name": "time_fraction", "dtype": "float64",
        "semantic_role": "known_time_varying_covariate",
    },
)

_OFFLINE_KEYS = frozenset({
    "schema_id", "synthetic_feasible", "generator_id", "generator_version",
    "entity_count", "family_fitting_prefix_steps", "supported_cadences",
    "forecast_horizon_demo_value", "tables",
})
_TABLE_KEYS = frozenset({"columns", "primary_key"})
_COLUMN_KEYS = frozenset({"name", "dtype", "semantic_role"})
_ATTEMPT_KEYS = frozenset({
    "host", "cited_url", "status", "reason", "http_code",
})
_ENTITY_COUNT = 8
_FAMILY_FITTING_PREFIX_STEPS = 24
_MAX_USABLE_STEPS = 100_000
_MAX_OBSERVATION_ROWS = 1_000_000
_ORIGIN = datetime(2000, 1, 3, tzinfo=timezone.utc)
_MICROSECONDS = {
    "week": Decimal(7 * 24 * 60 * 60 * 1_000_000),
    "day": Decimal(24 * 60 * 60 * 1_000_000),
    "hour": Decimal(60 * 60 * 1_000_000),
    "minute": Decimal(60 * 1_000_000),
    "second": Decimal(1_000_000),
}
# Fixed values avoid platform libm drift in generated bytes.
_SIN = tuple(Decimal(value) for value in (
    "0", "0.5", "0.866025403784", "1", "0.866025403784", "0.5",
    "0", "-0.5", "-0.866025403784", "-1", "-0.866025403784", "-0.5",
))
_COS = tuple(Decimal(value) for value in (
    "1", "0.866025403784", "0.5", "0", "-0.5", "-0.866025403784",
    "-1", "-0.866025403784", "-0.5", "0", "0.5", "0.866025403784",
))
HONESTY_NOTE = (
    "This family-owned synthetic offline fallback is not the paper's "
    "dataset. Numbers computed from it demonstrate package mechanics only; "
    "they are not paper-comparable or benchmark evidence."
)


@dataclass(frozen=True)
class OfflineFallbackOutcome:
    """Typed success or refusal; refusal means no canonical files published."""

    status: Literal["generated", "refused"]
    code: str
    reason: str
    provenance: dict[str, object] | None = None
    written_files: tuple[str, ...] = ()

    @property
    def generated(self) -> bool:
        return self.status == "generated"

    def as_dict(self) -> dict[str, object]:
        return {
            "status": self.status,
            "code": self.code,
            "reason": self.reason,
            "provenance": self.provenance,
            "written_files": list(self.written_files),
        }


class OfflineFallbackValidationError(ValueError):
    def __init__(self, code: str, message: str):
        super().__init__(message)
        self.code = code


@dataclass(frozen=True)
class _Quantity:
    role: str
    raw_value: int | float | None
    unit: str
    granularity: Decimal
    paper_value_status: str
    steps: int
    value_source: str
    paper_element_ids: tuple[str, ...]
    axis_paper_element_ids: tuple[str, ...]

    def provenance(self) -> dict[str, object]:
        return {
            "role": self.role,
            "raw_value": self.raw_value,
            "unit": self.unit,
            "granularity": _json_number(self.granularity),
            "paper_value_status": self.paper_value_status,
            "steps": self.steps,
            "value_source": self.value_source,
            "paper_element_ids": list(self.paper_element_ids),
            "axis_paper_element_ids": list(self.axis_paper_element_ids),
        }


@dataclass(frozen=True)
class _Plan:
    entity_count: int
    seed: int
    unit: str
    granularity: Decimal
    cadence_microseconds: int
    quantities: tuple[_Quantity, ...]
    family_fitting_prefix_steps: int
    usable_steps: int
    attempts: tuple[dict[str, object], ...]
    scheme: dict[str, object]
    family_contract: dict[str, object]

    @property
    def by_role(self) -> dict[str, _Quantity]:
        return {item.role: item for item in self.quantities}


def _canonical_json(value: object) -> str:
    try:
        return json.dumps(
            value, sort_keys=True, separators=(",", ":"), ensure_ascii=False,
            allow_nan=False,
        )
    except (TypeError, ValueError) as exc:
        raise OfflineFallbackValidationError(
            "offline_fallback_not_json", f"evidence is not canonical JSON: {exc}",
        ) from exc


def _digest(value: object) -> str:
    return hashlib.sha256(_canonical_json(value).encode("utf-8")).hexdigest()


def _json_number(value: Decimal) -> int | float:
    integral = value.to_integral_value()
    return int(integral) if value == integral else float(value)


def _object(value: object, root: str) -> Mapping[str, object]:
    if not isinstance(value, Mapping):
        raise OfflineFallbackValidationError(
            "offline_fallback_contract_shape", f"{root} must be an object",
        )
    return value


def _exact_keys(
    value: Mapping[str, object], expected: frozenset[str], root: str,
) -> None:
    keys = set(value)
    if keys != expected:
        raise OfflineFallbackValidationError(
            "offline_fallback_contract_shape",
            f"{root} has unsupported shape; missing={sorted(expected - keys)}, "
            f"unknown={sorted(keys - expected)}",
        )


def _positive_int(value: object, root: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
        raise OfflineFallbackValidationError(
            "offline_fallback_positive_integer",
            f"{root} must be a positive integer, got {value!r}",
        )
    return value


def _decimal(value: object, root: str) -> Decimal:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise OfflineFallbackValidationError(
            "offline_fallback_protocol_quantity",
            f"{root} must be a raw numeric JSON value, got {value!r}",
        )
    try:
        result = Decimal(str(value))
    except (InvalidOperation, ValueError) as exc:
        raise OfflineFallbackValidationError(
            "offline_fallback_protocol_quantity", f"{root} is not numeric",
        ) from exc
    if not result.is_finite() or result <= 0:
        raise OfflineFallbackValidationError(
            "offline_fallback_protocol_quantity",
            f"{root} must be finite and positive, got {value!r}",
        )
    return result


def _ids(value: object, root: str) -> tuple[str, ...]:
    if not isinstance(value, Sequence) or isinstance(value, (str, bytes)):
        raise OfflineFallbackValidationError(
            "offline_fallback_protocol_evidence",
            f"{root} must be a list of string ids",
        )
    result: list[str] = []
    for item in value:
        if not isinstance(item, str) or not item or item != item.strip():
            raise OfflineFallbackValidationError(
                "offline_fallback_protocol_evidence",
                f"{root} must contain nonblank already-stripped string ids",
            )
        result.append(item)
    if not result or len(result) != len(set(result)):
        raise OfflineFallbackValidationError(
            "offline_fallback_protocol_evidence",
            f"{root} must be nonempty and unique",
        )
    return tuple(result)


def _column(value: object, root: str) -> dict[str, str]:
    item = _object(value, root)
    _exact_keys(item, _COLUMN_KEYS, root)
    normalized: dict[str, str] = {}
    for key in ("name", "dtype", "semantic_role"):
        field = item.get(key)
        if not isinstance(field, str) or not field or field != field.strip():
            raise OfflineFallbackValidationError(
                "offline_fallback_contract_shape",
                f"{root}.{key} must be a nonblank string",
            )
        normalized[key] = field
    return normalized


def _table(
    value: object, root: str, expected_columns: tuple[dict[str, str], ...],
    expected_key: tuple[str, ...],
) -> dict[str, object]:
    item = _object(value, root)
    _exact_keys(item, _TABLE_KEYS, root)
    raw_columns = item.get("columns")
    if not isinstance(raw_columns, list):
        raise OfflineFallbackValidationError(
            "offline_fallback_contract_shape", f"{root}.columns must be a list",
        )
    columns = [_column(value, f"{root}.columns[{index}]")
               for index, value in enumerate(raw_columns)]
    if columns != list(expected_columns):
        raise OfflineFallbackValidationError(
            "offline_fallback_table_schema",
            f"{root}.columns disagree with the closed {SCHEMA_ID} schema",
        )
    primary_key = item.get("primary_key")
    if not isinstance(primary_key, list) or tuple(primary_key) != expected_key:
        raise OfflineFallbackValidationError(
            "offline_fallback_table_schema",
            f"{root}.primary_key must be {list(expected_key)!r}",
        )
    return {"columns": columns, "primary_key": list(expected_key)}


def _family_contract(build_plan: object) -> dict[str, object]:
    resolved = _object(build_plan, "build_plan")
    contract = _object(
        resolved.get("offline_demo_data"), "build_plan.offline_demo_data",
    )
    _exact_keys(contract, _OFFLINE_KEYS, "build_plan.offline_demo_data")
    if contract.get("schema_id") != SCHEMA_ID:
        raise OfflineFallbackValidationError(
            "offline_fallback_schema_unsupported",
            f"only schema_id={SCHEMA_ID!r} is supported",
        )
    if contract.get("synthetic_feasible") is not True:
        raise OfflineFallbackValidationError(
            "offline_fallback_not_feasible",
            "family contract must explicitly set synthetic_feasible=true",
        )
    if (contract.get("generator_id"), contract.get("generator_version")) != (
        GENERATOR_ID, GENERATOR_VERSION,
    ):
        raise OfflineFallbackValidationError(
            "offline_fallback_generator_unsupported",
            f"family contract must select {GENERATOR_ID} {GENERATOR_VERSION}",
        )
    entity_count = _positive_int(
        contract.get("entity_count"), "offline_demo_data.entity_count",
    )
    if entity_count != _ENTITY_COUNT:
        raise OfflineFallbackValidationError(
            "offline_fallback_entity_contract",
            f"{SCHEMA_ID} v1 requires entity_count={_ENTITY_COUNT}",
        )
    fitting_prefix = _positive_int(
        contract.get("family_fitting_prefix_steps"),
        "offline_demo_data.family_fitting_prefix_steps",
    )
    if fitting_prefix != _FAMILY_FITTING_PREFIX_STEPS:
        raise OfflineFallbackValidationError(
            "offline_fallback_fitting_capacity_contract",
            f"{SCHEMA_ID} v1 requires family_fitting_prefix_steps="
            f"{_FAMILY_FITTING_PREFIX_STEPS}",
        )
    cadences = contract.get("supported_cadences")
    if not isinstance(cadences, list) or tuple(cadences) != SUPPORTED_CADENCES:
        raise OfflineFallbackValidationError(
            "offline_fallback_cadence_contract",
            f"supported_cadences must be {list(SUPPORTED_CADENCES)!r}",
        )
    horizon = _positive_int(
        contract.get("forecast_horizon_demo_value"),
        "offline_demo_data.forecast_horizon_demo_value",
    )
    tables = _object(contract.get("tables"), "offline_demo_data.tables")
    if set(tables) != {SERIES_FILENAME, OBSERVATIONS_FILENAME}:
        raise OfflineFallbackValidationError(
            "offline_fallback_table_schema",
            "tables must contain exactly series.csv and observations.csv",
        )
    normalized_tables = {
        SERIES_FILENAME: _table(
            tables[SERIES_FILENAME], f"tables.{SERIES_FILENAME}",
            SERIES_COLUMNS, ("series_id",),
        ),
        OBSERVATIONS_FILENAME: _table(
            tables[OBSERVATIONS_FILENAME], f"tables.{OBSERVATIONS_FILENAME}",
            OBSERVATION_COLUMNS, ("series_id", "timestamp"),
        ),
    }
    return {
        "schema_id": SCHEMA_ID,
        "synthetic_feasible": True,
        "generator_id": GENERATOR_ID,
        "generator_version": GENERATOR_VERSION,
        "entity_count": entity_count,
        "family_fitting_prefix_steps": fitting_prefix,
        "supported_cadences": list(SUPPORTED_CADENCES),
        "forecast_horizon_demo_value": horizon,
        "tables": normalized_tables,
    }


def _attempts(value: object) -> tuple[dict[str, object], ...]:
    if not isinstance(value, Sequence) or isinstance(value, (str, bytes)):
        raise OfflineFallbackValidationError(
            "offline_fallback_attempt_trail",
            "acquisition_attempts must be a list of typed records",
        )
    normalized: list[dict[str, object]] = []
    for index, raw in enumerate(value):
        root = f"acquisition_attempts[{index}]"
        item = _object(raw, root)
        _exact_keys(item, _ATTEMPT_KEYS, root)
        record: dict[str, object] = {}
        for key in ("status", "reason"):
            field = item.get(key)
            if not isinstance(field, str) or not field or field != field.strip():
                raise OfflineFallbackValidationError(
                    "offline_fallback_attempt_trail",
                    f"{root}.{key} must be a nonblank string",
                )
            record[key] = field
        for key in ("host", "cited_url"):
            field = item.get(key)
            if field is not None and (
                not isinstance(field, str) or not field
                or field != field.strip()
            ):
                raise OfflineFallbackValidationError(
                    "offline_fallback_attempt_trail",
                    f"{root}.{key} must be null or a nonblank string",
                )
            record[key] = field
        http_code = item.get("http_code")
        if http_code is not None and (
            isinstance(http_code, bool) or not isinstance(http_code, int)
            or not 100 <= http_code <= 599
        ):
            raise OfflineFallbackValidationError(
                "offline_fallback_attempt_trail",
                f"{root}.http_code must be null or 100..599",
            )
        record["http_code"] = http_code
        normalized.append(record)
    return tuple(normalized)


def _steps(value: Decimal, granularity: Decimal, root: str) -> int:
    result = value / granularity
    if result <= 0 or result != result.to_integral_value():
        raise OfflineFallbackValidationError(
            "offline_fallback_protocol_nonintegral",
            f"{root}={value} is not positive integral steps at "
            f"granularity={granularity}",
        )
    return int(result)


def _protocol(
    spec: object, contract: Mapping[str, object],
) -> tuple[tuple[_Quantity, ...], str, Decimal, int, dict[str, object]]:
    method_spec = _object(spec, "method_spec")
    comparison = _object(method_spec.get("comparison"), "method_spec.comparison")
    classification = _object(
        comparison.get("classification"), "comparison.classification",
    )
    family_id = classification.get("id")
    if family_id not in SUPPORTED_FAMILY_IDS:
        raise OfflineFallbackValidationError(
            "offline_fallback_family_unsupported",
            f"unsupported classification.id={family_id!r}",
        )
    data_requirements = _object(
        method_spec.get("data_requirements"), "method_spec.data_requirements",
    )
    if data_requirements.get("synthetic_feasible") is not True:
        raise OfflineFallbackValidationError(
            "offline_fallback_not_feasible",
            "method_spec.data_requirements.synthetic_feasible must be true",
        )
    protocol = _object(
        comparison.get("evaluation_protocol"), "comparison.evaluation_protocol",
    )
    scheme = _object(protocol.get("scheme"), "evaluation_protocol.scheme")
    if scheme.get("kind") != "single_holdout":
        raise OfflineFallbackValidationError(
            "offline_fallback_protocol_unsupported",
            "only typed single_holdout evaluation is supported",
        )
    if scheme.get("paper_value_status") != "paper_stated":
        raise OfflineFallbackValidationError(
            "offline_fallback_protocol_unsupported",
            "single_holdout scheme must be paper_stated",
        )
    scheme_ids = _ids(
        scheme.get("paper_element_ids"), "scheme.paper_element_ids",
    )
    raw_quantities = protocol.get("quantities")
    if not isinstance(raw_quantities, list):
        raise OfflineFallbackValidationError(
            "offline_fallback_protocol_roles",
            "evaluation_protocol.quantities must be a list",
        )
    by_role: dict[str, Mapping[str, object]] = {}
    for index, raw in enumerate(raw_quantities):
        item = _object(raw, f"evaluation_protocol.quantities[{index}]")
        role = item.get("role")
        if role not in PROTOCOL_ROLES or role in by_role:
            raise OfflineFallbackValidationError(
                "offline_fallback_protocol_roles",
                f"expected exactly one quantity per role {list(PROTOCOL_ROLES)!r}",
            )
        by_role[str(role)] = item
    if set(by_role) != set(PROTOCOL_ROLES):
        raise OfflineFallbackValidationError(
            "offline_fallback_protocol_roles",
            f"expected exactly one quantity per role {list(PROTOCOL_ROLES)!r}",
        )

    raw_units = [item.get("unit") for item in by_role.values()]
    if any(not isinstance(unit, str) for unit in raw_units):
        raise OfflineFallbackValidationError(
            "offline_fallback_protocol_cadence_disagreement",
            "every protocol unit must be a canonical string",
        )
    granularity_values = [
        _decimal(item.get("granularity"), f"{role}.granularity")
        for role, item in by_role.items()
    ]
    if len(set(raw_units)) != 1 or len(set(granularity_values)) != 1:
        raise OfflineFallbackValidationError(
            "offline_fallback_protocol_cadence_disagreement",
            "C, K, V, and T must use one identical unit and granularity",
        )
    unit = raw_units[0]
    if unit not in contract["supported_cadences"]:
        raise OfflineFallbackValidationError(
            "offline_fallback_cadence_unsupported",
            f"cadence {unit!r} is outside {contract['supported_cadences']!r}",
        )
    granularity = granularity_values[0]
    cadence_raw = _MICROSECONDS[str(unit)] * granularity
    if cadence_raw != cadence_raw.to_integral_value():
        raise OfflineFallbackValidationError(
            "offline_fallback_cadence_precision",
            "cadence is not exactly representable at microsecond precision",
        )
    cadence_microseconds = int(cadence_raw)

    normalized: list[_Quantity] = []
    demo_horizon = int(contract["forecast_horizon_demo_value"])
    for role in PROTOCOL_ROLES:
        item = by_role[role]
        root = f"evaluation_protocol.quantities[role={role}]"
        status = item.get("paper_value_status")
        raw_value = item.get("value")
        if role == "forecast_call_horizon" and status == "paper_unspecified":
            if raw_value is not None:
                raise OfflineFallbackValidationError(
                    "offline_fallback_horizon_authority",
                    f"{root}.value must be null when paper_unspecified",
                )
            role_steps = demo_horizon
            value_source = (
                "build_plan.offline_demo_data.forecast_horizon_demo_value"
            )
            normalized_raw = None
        elif status == "paper_stated":
            physical_value = _decimal(raw_value, f"{root}.value")
            role_steps = _steps(physical_value, granularity, f"{root}.value")
            value_source = "method_spec.comparison.evaluation_protocol"
            normalized_raw = raw_value
        else:
            raise OfflineFallbackValidationError(
                "offline_fallback_protocol_value_missing",
                "C, V, and T must be paper_stated; K must be paper_stated or "
                "paper_unspecified with a resolved family demo value",
            )
        normalized.append(_Quantity(
            role=role,
            raw_value=normalized_raw,
            unit=str(unit),
            granularity=granularity,
            paper_value_status=str(status),
            steps=role_steps,
            value_source=value_source,
            paper_element_ids=_ids(
                item.get("paper_element_ids"), f"{root}.paper_element_ids",
            ),
            axis_paper_element_ids=_ids(
                item.get("axis_paper_element_ids"),
                f"{root}.axis_paper_element_ids",
            ),
        ))
    scheme_provenance = {
        "kind": "single_holdout",
        "paper_value_status": "paper_stated",
        "paper_element_ids": list(scheme_ids),
    }
    return (
        tuple(normalized), str(unit), granularity, cadence_microseconds,
        scheme_provenance,
    )


def _plan(
    spec: object, build_plan: object, seed: object, acquisition_attempts: object,
) -> _Plan:
    contract = _family_contract(build_plan)
    if isinstance(seed, bool) or not isinstance(seed, int) \
            or not 0 <= seed <= 2**63 - 1:
        raise OfflineFallbackValidationError(
            "offline_fallback_seed", "seed must be an integer in 0..2^63-1",
        )
    quantities, unit, granularity, cadence, scheme = _protocol(spec, contract)
    roles = {item.role: item for item in quantities}
    context = roles["context_length"].steps
    horizon = roles["forecast_call_horizon"].steps
    validation = roles["validation_span"].steps
    test = roles["test_span"].steps
    if horizon > validation:
        raise OfflineFallbackValidationError(
            "offline_fallback_horizon_exceeds_validation",
            f"K={horizon} exceeds V={validation}",
        )
    if horizon > test:
        raise OfflineFallbackValidationError(
            "offline_fallback_horizon_exceeds_test",
            f"K={horizon} exceeds T={test}",
        )
    # R2C-065 owns static single-holdout axis capacity. Forecast-call K is a
    # separate per-call constraint and must not be folded into the dataset
    # extent or used to invent a fitting partition.
    fitting_prefix = int(contract["family_fitting_prefix_steps"])
    usable = fitting_prefix + context + validation + test
    entity_count = int(contract["entity_count"])
    if usable > _MAX_USABLE_STEPS \
            or usable * entity_count > _MAX_OBSERVATION_ROWS:
        raise OfflineFallbackValidationError(
            "offline_fallback_capacity_limit",
            f"full panel {entity_count}x{usable} exceeds the demo limit",
        )
    try:
        _ORIGIN + timedelta(
            microseconds=cadence * (usable - 1),
        )
    except OverflowError as exc:
        raise OfflineFallbackValidationError(
            "offline_fallback_timestamp_overflow",
            "protocol capacity and cadence exceed the timestamp range",
        ) from exc
    return _Plan(
        entity_count=entity_count,
        seed=seed,
        unit=unit,
        granularity=granularity,
        cadence_microseconds=cadence,
        quantities=quantities,
        family_fitting_prefix_steps=fitting_prefix,
        usable_steps=usable,
        attempts=_attempts(acquisition_attempts),
        scheme=scheme,
        family_contract=contract,
    )


def _entity_ids(count: int) -> tuple[str, ...]:
    return tuple(f"series_{index:03d}" for index in range(count))


def _decimal_text(value: Decimal) -> str:
    return format(value.quantize(Decimal("0.000000000001")), "f")


def _timestamp_text(value: datetime) -> str:
    timespec = "microseconds" if value.microsecond else "seconds"
    return value.isoformat(timespec=timespec).replace("+00:00", "Z")


def _timestamps(plan: _Plan) -> tuple[str, ...]:
    return tuple(
        _timestamp_text(
            _ORIGIN + timedelta(
                microseconds=plan.cadence_microseconds * step,
            )
        )
        for step in range(plan.usable_steps)
    )


def _jitter(seed: int, series_id: str, step: int) -> Decimal:
    identity = (
        f"{GENERATOR_VERSION}|{seed}|{series_id}|{step}".encode("utf-8")
    )
    bucket = int.from_bytes(hashlib.sha256(identity).digest()[:8], "big")
    unit_interval = Decimal(bucket) / Decimal(2**64 - 1)
    return (unit_interval * Decimal(2) - Decimal(1)) * Decimal("0.25")


def _series_payload(plan: _Plan) -> bytes:
    output = io.StringIO(newline="")
    writer = csv.writer(output, lineterminator="\n")
    writer.writerow([column["name"] for column in SERIES_COLUMNS])
    for index, series_id in enumerate(_entity_ids(plan.entity_count)):
        level = Decimal("20") + Decimal(index) * Decimal("1.5")
        amplitude = Decimal("3") + Decimal(index % 4) * Decimal("0.25")
        writer.writerow([
            series_id, _decimal_text(level), _decimal_text(amplitude),
        ])
    return output.getvalue().encode("utf-8")


def _observations_payload(plan: _Plan) -> bytes:
    output = io.StringIO(newline="")
    writer = csv.writer(output, lineterminator="\n")
    writer.writerow([column["name"] for column in OBSERVATION_COLUMNS])
    timestamps = _timestamps(plan)
    denominator = Decimal(plan.usable_steps - 1)
    for entity_index, series_id in enumerate(_entity_ids(plan.entity_count)):
        level = Decimal("20") + Decimal(entity_index) * Decimal("1.5")
        amplitude = Decimal("3") + Decimal(entity_index % 4) * Decimal("0.25")
        for step, timestamp in enumerate(timestamps):
            season_sin = _SIN[step % 12]
            season_cos = _COS[step % 12]
            time_fraction = Decimal(step) / denominator
            target = (
                level + amplitude * season_sin
                + Decimal("0.25") * amplitude * season_cos
                + Decimal("0.05") * Decimal(step)
                + _jitter(plan.seed, series_id, step)
            )
            writer.writerow([
                series_id,
                timestamp,
                _decimal_text(target),
                _decimal_text(season_sin),
                _decimal_text(season_cos),
                _decimal_text(time_fraction),
            ])
    return output.getvalue().encode("utf-8")


def _file_record(
    filename: str, payload: bytes, rows: int, table: Mapping[str, object],
    plan: _Plan,
) -> dict[str, object]:
    record: dict[str, object] = {
        "file": filename,
        "rows_kept": rows,
        "truncated": False,
        "sha256": hashlib.sha256(payload).hexdigest(),
        "bytes": len(payload),
        "columns": table["columns"],
        "primary_key": table["primary_key"],
        "entity_column": "series_id",
        "entities_kept": plan.entity_count,
        "entities_in_source": plan.entity_count,
        "entity_filter_applied": False,
    }
    if filename == OBSERVATIONS_FILENAME:
        timestamps = _timestamps(plan)
        record["time_axis"] = {
            "column": "timestamp",
            "steps_kept": plan.usable_steps,
            "steps_in_source": plan.usable_steps,
            "first_step": timestamps[0],
            "last_step": timestamps[-1],
            "rows_per_step_cap": None,
            "entity_column": "series_id",
            "entities_kept": plan.entity_count,
            "entities_in_source": plan.entity_count,
            "live_steps": plan.usable_steps,
            "last_live_step": timestamps[-1],
            "dead_tail_columns": [],
            "source_cadence": {
                "unit": plan.unit,
                "granularity": _json_number(plan.granularity),
            },
        }
    return record


def _mechanics() -> dict[str, object]:
    return {
        "panel_layout": "full_entity_by_timestamp_cartesian_panel",
        "row_order": ["series_id", "timestamp"],
        "entity_id_format": "series_{zero_based_index:03d}",
        "timestamp_origin": _timestamp_text(_ORIGIN),
        "season_period_steps": 12,
        "static_level_formula": "20 + 1.5 * entity_index",
        "static_amplitude_formula": "3 + 0.25 * (entity_index mod 4)",
        "season_covariates": "fixed 12-step decimal sine/cosine lookup",
        "time_fraction_formula": "step_index / (usable_steps - 1)",
        "target_formula": (
            "static_level + static_amplitude*season_sin + "
            "0.25*static_amplitude*season_cos + 0.05*step_index + jitter"
        ),
        "jitter": {
            "algorithm": "sha256",
            "input_utf8": (
                "{generator_version}|{seed}|{series_id}|{step_index}"
            ),
            "extract": "first_8_bytes_unsigned_big_endian",
            "mapping": "linear [0,2^64-1] to [-0.25,0.25]",
            "random_library_used": False,
        },
    }


def _manifest(
    plan: _Plan, series_payload: bytes, observations_payload: bytes,
) -> dict[str, object]:
    by_role = plan.by_role
    tables = plan.family_contract["tables"]
    timestamps = _timestamps(plan)
    manifest: dict[str, object] = {
        "schema_version": PROVENANCE_SCHEMA_VERSION,
        "schema_id": SCHEMA_ID,
        "tier": SYNTHETIC_TIER,
        "generator": {
            "name": GENERATOR_ID,
            "version": GENERATOR_VERSION,
            "seed": plan.seed,
        },
        "files": [
            _file_record(
                SERIES_FILENAME,
                series_payload,
                plan.entity_count,
                tables[SERIES_FILENAME],
                plan,
            ),
            _file_record(
                OBSERVATIONS_FILENAME,
                observations_payload,
                plan.entity_count * plan.usable_steps,
                tables[OBSERVATIONS_FILENAME],
                plan,
            ),
        ],
        "entity_ids": list(_entity_ids(plan.entity_count)),
        "entity_mapping": [
            {"position": position, "series_id": series_id}
            for position, series_id in enumerate(_entity_ids(plan.entity_count))
        ],
        "cadence": {
            "unit": plan.unit,
            "step": _json_number(plan.granularity),
            "first_timestamp": timestamps[0],
            "last_timestamp": timestamps[-1],
            "regular": True,
        },
        "protocol_capacity": {
            "scheme": plan.scheme,
            "quantities": [
                by_role[role].provenance() for role in PROTOCOL_ROLES
            ],
            "context_steps": by_role["context_length"].steps,
            "forecast_horizon_steps": by_role["forecast_call_horizon"].steps,
            "validation_steps": by_role["validation_span"].steps,
            "test_steps": by_role["test_span"].steps,
            "family_fitting_prefix_steps": plan.family_fitting_prefix_steps,
            "static_axis_floor_steps": (
                by_role["context_length"].steps
                + by_role["validation_span"].steps
                + by_role["test_span"].steps
            ),
            "usable_steps": plan.usable_steps,
            "static_axis_formula": "C + V + T",
            "usable_formula": "family_fitting_prefix_steps + C + V + T",
            "fitting_prefix_authority": (
                "build_plan.offline_demo_data.family_fitting_prefix_steps"
            ),
            "forecast_call_checks": {
                "K_lte_validation_span": True,
                "K_lte_test_span": True,
                "C_plus_K_lte_usable_axis": (
                    by_role["context_length"].steps
                    + by_role["forecast_call_horizon"].steps
                    <= plan.usable_steps
                ),
            },
            "capacity_only": True,
            "capacity_limit": (
                "The family-owned prefix supplies fitting capacity but does "
                "not certify the generated code's actual fitting partition. "
                "Static capacity does not certify "
                "forecast origins, target lineage, or generated-code "
                "protocol use. K remains a separate per-call quantity."
            ),
        },
        "generation_mechanics": _mechanics(),
        "acquisition_attempts": list(plan.attempts),
        "honesty_note": HONESTY_NOTE,
    }
    manifest["bundle_digest"] = _digest(manifest)
    return manifest


def _csv_rows(payload: bytes, filename: str) -> tuple[list[str], list[dict[str, str]]]:
    try:
        text = payload.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise OfflineFallbackValidationError(
            "offline_fallback_bundle_encoding", f"{filename} is not UTF-8",
        ) from exc
    reader = csv.DictReader(io.StringIO(text, newline=""))
    if reader.fieldnames is None:
        raise OfflineFallbackValidationError(
            "offline_fallback_bundle_header", f"{filename} has no header",
        )
    rows = list(reader)
    if any(None in row for row in rows):
        raise OfflineFallbackValidationError(
            "offline_fallback_bundle_rows", f"{filename} has over-wide rows",
        )
    return list(reader.fieldnames), rows


def _finite(value: str, root: str) -> float:
    try:
        result = float(value)
    except ValueError as exc:
        raise OfflineFallbackValidationError(
            "offline_fallback_bundle_dtype", f"{root} is not float64 text",
        ) from exc
    if not math.isfinite(result):
        raise OfflineFallbackValidationError(
            "offline_fallback_bundle_dtype", f"{root} must be finite",
        )
    return result


def _parse_timestamp(value: str, root: str) -> datetime:
    if not value.endswith("Z"):
        raise OfflineFallbackValidationError(
            "offline_fallback_bundle_timestamp",
            f"{root} must be ISO-8601 UTC ending in Z",
        )
    try:
        result = datetime.fromisoformat(value[:-1] + "+00:00")
    except ValueError as exc:
        raise OfflineFallbackValidationError(
            "offline_fallback_bundle_timestamp", f"{root} is not ISO-8601",
        ) from exc
    if result.tzinfo != timezone.utc:
        raise OfflineFallbackValidationError(
            "offline_fallback_bundle_timestamp", f"{root} is not UTC",
        )
    return result


def _validate_payloads(
    series_payload: bytes, observations_payload: bytes, plan: _Plan,
) -> None:
    series_header, series_rows = _csv_rows(series_payload, SERIES_FILENAME)
    expected_series_header = [item["name"] for item in SERIES_COLUMNS]
    if series_header != expected_series_header:
        raise OfflineFallbackValidationError(
            "offline_fallback_bundle_header",
            f"{SERIES_FILENAME} header must be {expected_series_header!r}",
        )
    expected_ids = list(_entity_ids(plan.entity_count))
    actual_ids = [row["series_id"] for row in series_rows]
    if actual_ids != expected_ids or len(actual_ids) != len(set(actual_ids)):
        raise OfflineFallbackValidationError(
            "offline_fallback_bundle_entity_ids",
            f"{SERIES_FILENAME} must carry the stable sorted entity ids",
        )
    for index, row in enumerate(series_rows):
        _finite(row["static_level"], f"series[{index}].static_level")
        amplitude = _finite(
            row["static_amplitude"], f"series[{index}].static_amplitude",
        )
        if amplitude <= 0:
            raise OfflineFallbackValidationError(
                "offline_fallback_bundle_dtype",
                f"series[{index}].static_amplitude must be positive",
            )

    obs_header, obs_rows = _csv_rows(
        observations_payload, OBSERVATIONS_FILENAME,
    )
    expected_obs_header = [item["name"] for item in OBSERVATION_COLUMNS]
    if obs_header != expected_obs_header:
        raise OfflineFallbackValidationError(
            "offline_fallback_bundle_header",
            f"{OBSERVATIONS_FILENAME} header must be {expected_obs_header!r}",
        )
    timestamps = list(_timestamps(plan))
    expected_keys = [
        (series_id, timestamp)
        for series_id in expected_ids
        for timestamp in timestamps
    ]
    actual_keys = [(row["series_id"], row["timestamp"]) for row in obs_rows]
    if actual_keys != expected_keys or len(actual_keys) != len(set(actual_keys)):
        raise OfflineFallbackValidationError(
            "offline_fallback_bundle_full_panel",
            "observations.csv must be the sorted full Cartesian panel of "
            "stable ids and regular timestamps",
        )
    parsed = [
        _parse_timestamp(value, f"timestamp[{index}]")
        for index, value in enumerate(timestamps)
    ]
    expected_delta = timedelta(microseconds=plan.cadence_microseconds)
    if any(
        right - left != expected_delta
        for left, right in zip(parsed, parsed[1:])
    ):
        raise OfflineFallbackValidationError(
            "offline_fallback_bundle_cadence",
            "observations.csv timestamps are not exactly regular",
        )
    for index, row in enumerate(obs_rows):
        for column in ("target", "season_sin", "season_cos", "time_fraction"):
            _finite(row[column], f"observations[{index}].{column}")


def _validate_manifest(
    manifest: object, series_payload: bytes, observations_payload: bytes,
    plan: _Plan,
) -> dict[str, object]:
    value = _object(manifest, PROVENANCE_FILENAME)
    normalized = json.loads(_canonical_json(dict(value)))
    recorded_digest = normalized.pop("bundle_digest", None)
    if not isinstance(recorded_digest, str) \
            or len(recorded_digest) != 64 \
            or recorded_digest != _digest(normalized):
        raise OfflineFallbackValidationError(
            "offline_fallback_bundle_digest",
            "PROVENANCE.json digest does not bind its canonical contents",
        )
    expected = _manifest(plan, series_payload, observations_payload)
    if dict(value) != expected:
        raise OfflineFallbackValidationError(
            "offline_fallback_provenance_disagreement",
            "PROVENANCE.json does not exactly describe the validated tables",
        )
    normalized["bundle_digest"] = recorded_digest
    return normalized


def _validate_stage(stage: Path, plan: _Plan) -> dict[str, object]:
    try:
        series_payload = (stage / SERIES_FILENAME).read_bytes()
        observations_payload = (stage / OBSERVATIONS_FILENAME).read_bytes()
        manifest = json.loads(
            (stage / PROVENANCE_FILENAME).read_text(encoding="utf-8")
        )
    except (OSError, json.JSONDecodeError) as exc:
        raise OfflineFallbackValidationError(
            "offline_fallback_staged_bundle",
            f"staged bundle is unreadable: {exc}",
        ) from exc
    _validate_payloads(series_payload, observations_payload, plan)
    return _validate_manifest(
        manifest, series_payload, observations_payload, plan,
    )


def _destination_conflicts(destination: Path) -> list[str]:
    return [
        filename for filename in PUBLISHED_FILENAMES
        if (destination / filename).exists()
    ]


def _file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _transaction_record(stage: Path) -> dict[str, object]:
    return {
        "schema_version": "1.0.0",
        "generator_id": GENERATOR_ID,
        "generator_version": GENERATOR_VERSION,
        "files": [
            {"file": filename, "sha256": _file_sha256(stage / filename)}
            for filename in PUBLISHED_FILENAMES
        ],
    }


def recover_interrupted_time_series_fallback(destination: Path) -> bool:
    """Remove only hash-matched files from an interrupted owned publication.

    The marker is installed before the first canonical rename. A later Stage
    2a invocation can therefore distinguish generator-owned partial files from
    researcher data. Any malformed marker or changed file refuses recovery and
    preserves every file.
    """
    destination = Path(destination)
    marker = destination / TRANSACTION_FILENAME
    if not marker.is_file():
        return False
    try:
        record = json.loads(marker.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise OfflineFallbackValidationError(
            "offline_fallback_transaction_marker",
            f"interrupted-publication marker is unreadable: {exc}",
        ) from exc
    expected_keys = {
        "schema_version", "generator_id", "generator_version", "files",
    }
    if (
        not isinstance(record, dict)
        or set(record) != expected_keys
        or record.get("schema_version") != "1.0.0"
        or record.get("generator_id") != GENERATOR_ID
        or record.get("generator_version") != GENERATOR_VERSION
        or not isinstance(record.get("files"), list)
    ):
        raise OfflineFallbackValidationError(
            "offline_fallback_transaction_marker",
            "interrupted-publication marker does not match the closed schema",
        )
    expected: dict[str, str] = {}
    for item in record["files"]:
        if (
            not isinstance(item, dict)
            or set(item) != {"file", "sha256"}
            or item.get("file") not in PUBLISHED_FILENAMES
            or not isinstance(item.get("sha256"), str)
            or len(item["sha256"]) != 64
        ):
            raise OfflineFallbackValidationError(
                "offline_fallback_transaction_marker",
                "interrupted-publication marker has an invalid file record",
            )
        expected[item["file"]] = item["sha256"]
    if set(expected) != set(PUBLISHED_FILENAMES):
        raise OfflineFallbackValidationError(
            "offline_fallback_transaction_marker",
            "interrupted-publication marker does not name the exact bundle",
        )
    for filename, digest in expected.items():
        target = destination / filename
        if target.exists() and (
            not target.is_file() or _file_sha256(target) != digest
        ):
            raise OfflineFallbackValidationError(
                "offline_fallback_transaction_conflict",
                f"refusing to remove changed interrupted file {filename!r}",
            )
    for filename in PUBLISHED_FILENAMES:
        (destination / filename).unlink(missing_ok=True)
    marker.unlink()
    return True


def _publish(stage: Path, destination: Path) -> None:
    if destination.exists() and not destination.is_dir():
        raise OfflineFallbackValidationError(
            "offline_fallback_destination",
            f"destination {destination} is not a directory",
        )
    conflicts = _destination_conflicts(destination)
    if conflicts:
        raise OfflineFallbackValidationError(
            "offline_fallback_destination_conflict",
            f"refusing to overwrite canonical files {conflicts!r}",
        )
    created = not destination.exists()
    destination.mkdir(parents=True, exist_ok=True)
    marker = destination / TRANSACTION_FILENAME
    marker_temp = stage / TRANSACTION_FILENAME
    published: list[Path] = []
    try:
        marker_temp.write_text(
            _canonical_json(_transaction_record(stage)) + "\n",
            encoding="utf-8",
        )
        os.replace(marker_temp, marker)
        # PROVENANCE.json is the completion marker and is moved last.
        for filename in PUBLISHED_FILENAMES:
            target = destination / filename
            if target.exists():
                raise FileExistsError(f"destination appeared during publish: {target}")
            source = stage / filename
            try:
                os.replace(source, target)
            except Exception:
                # A filesystem may report failure after completing the rename.
                # The vanished private source proves that this canonical file
                # belongs to this publication and must join rollback.
                if not source.exists() and target.exists():
                    published.append(target)
                raise
            else:
                published.append(target)
        marker.unlink()
    except Exception:
        for target in reversed(published):
            target.unlink(missing_ok=True)
        marker.unlink(missing_ok=True)
        marker_temp.unlink(missing_ok=True)
        if created:
            try:
                destination.rmdir()
            except OSError:
                pass
        raise


def generate_time_series_offline_fallback(
    spec: Mapping[str, object],
    build_plan: Mapping[str, object],
    destination: Path,
    *,
    seed: int,
    acquisition_attempts: Sequence[Mapping[str, object]],
    staging_parent: Path | None = None,
) -> OfflineFallbackOutcome:
    """Validate, stage, validate again, and publish the closed fallback.

    Unsupported or contradictory authority returns status=refused without
    publishing series.csv, observations.csv, or PROVENANCE.json.
    """
    try:
        plan = _plan(spec, build_plan, seed, acquisition_attempts)
        destination = Path(destination)
        if destination.exists() and not destination.is_dir():
            raise OfflineFallbackValidationError(
                "offline_fallback_destination",
                f"destination {destination} is not a directory",
            )
        recover_interrupted_time_series_fallback(destination)
        conflicts = _destination_conflicts(destination)
        if conflicts:
            raise OfflineFallbackValidationError(
                "offline_fallback_destination_conflict",
                f"refusing to overwrite canonical files {conflicts!r}",
            )
        series_payload = _series_payload(plan)
        observations_payload = _observations_payload(plan)
        _validate_payloads(series_payload, observations_payload, plan)
        manifest = _manifest(plan, series_payload, observations_payload)
        _validate_manifest(
            manifest, series_payload, observations_payload, plan,
        )
        destination.parent.mkdir(parents=True, exist_ok=True)
        stage_parent = (
            Path(staging_parent) if staging_parent is not None
            else destination.parent
        )
        stage_parent.mkdir(parents=True, exist_ok=True)
        with tempfile.TemporaryDirectory(
            prefix=".r2c-tsf-offline-", dir=stage_parent,
        ) as temporary:
            stage = Path(temporary)
            (stage / SERIES_FILENAME).write_bytes(series_payload)
            (stage / OBSERVATIONS_FILENAME).write_bytes(observations_payload)
            (stage / PROVENANCE_FILENAME).write_text(
                json.dumps(
                    manifest, indent=2, ensure_ascii=False, allow_nan=False,
                ) + "\n",
                encoding="utf-8",
            )
            normalized = _validate_stage(stage, plan)
            _publish(stage, destination)
        return OfflineFallbackOutcome(
            status="generated",
            code="offline_fallback_generated",
            reason=(
                f"generated {plan.entity_count} stable series x "
                f"{plan.usable_steps} regular {plan.unit} steps"
            ),
            provenance=normalized,
            written_files=PUBLISHED_FILENAMES,
        )
    except OfflineFallbackValidationError as exc:
        return OfflineFallbackOutcome(
            status="refused", code=exc.code, reason=str(exc),
        )
    except OSError as exc:
        return OfflineFallbackOutcome(
            status="refused",
            code="offline_fallback_write_failed",
            reason=f"offline fallback write failed without publication: {exc}",
        )


__all__ = [
    "GENERATOR_ID",
    "GENERATOR_VERSION",
    "OBSERVATIONS_FILENAME",
    "OfflineFallbackOutcome",
    "OfflineFallbackValidationError",
    "PROVENANCE_FILENAME",
    "SCHEMA_ID",
    "SERIES_FILENAME",
    "SUPPORTED_CADENCES",
    "SYNTHETIC_TIER",
    "TRANSACTION_FILENAME",
    "generate_time_series_offline_fallback",
    "recover_interrupted_time_series_fallback",
]
