"""Bounded notebook value-flow proof for structured training history.

Version one deliberately accepts only the direct schema-2 shape generated by
the forecasting notebook contract:

* one top-level declared fitting call;
* its mapping result indexed by the exact ``training_history`` key; and
* that value serialized by canonical ``json.dumps`` into the sole marker
  ``print``.

Supported direct disagreements are producer-owned.  Plausible flows that cross
function/helper or control-flow boundaries are not guessed: they are pipeline
coverage and do not consume a producer retry.
"""

from __future__ import annotations

import ast
import json
from collections.abc import Mapping, Sequence
from pathlib import Path

from scripts.time_series_training_history import (
    TrainingHistoryCoverageError,
    TrainingHistoryProducerError,
)


TRAINING_HISTORY_MARKER = "R2C_TRAINING_HISTORY_JSON: "


def training_history_notebook_applicable(
    run_dir: Path,
    build_plan: Mapping[str, object] | None,
) -> bool:
    """Whether a run exposes the typed schema-2 history boundary.

    The plan arm makes training history mandatory for this family.  Once a
    schema-2 architecture contract exists, a missing or malformed
    ``training_loop`` is therefore a producer disagreement, not a reason to
    silently make the evidence non-applicable.
    """
    if not isinstance(build_plan, Mapping) \
            or "training_history_execution" not in build_plan:
        return False
    try:
        contract = json.loads(
            (Path(run_dir) / ".pipeline" / "arch_contract.json").read_text(
                encoding="utf-8"
            )
        )
    except (OSError, json.JSONDecodeError):
        return False
    return (
        isinstance(contract, Mapping)
        and contract.get("schema_version") == "2.0.0"
    )


def _flow_contract(
    build_plan: Mapping[str, object],
) -> tuple[str, str, str]:
    execution = build_plan.get("training_history_execution")
    training = (
        execution.get("training_call")
        if isinstance(execution, Mapping) else None
    )
    result = (
        training.get("history_result")
        if isinstance(training, Mapping) else None
    )
    callable_name = (
        training.get("callable") if isinstance(training, Mapping) else None
    )
    module_name = (
        training.get("module") if isinstance(training, Mapping) else None
    )
    key = result.get("key") if isinstance(result, Mapping) else None
    if not isinstance(module_name, str) or not module_name \
            or not isinstance(callable_name, str) or not callable_name \
            or not isinstance(result, Mapping) \
            or result.get("kind") != "mapping_key" \
            or not isinstance(key, str) or not key:
        raise TrainingHistoryCoverageError(
            "training_history_notebook_plan_unsupported",
            "training_history_execution does not expose one declared fitting "
            "module/callable and exact mapping-key result",
        )
    return module_name, callable_name, key


def validate_training_history_architecture_contract(
    run_dir: Path,
    build_plan: Mapping[str, object],
) -> dict[str, str]:
    """Require the plan-mandated fitting entry on a schema-2 contract."""
    training_module, training_callable, _ = _flow_contract(build_plan)
    try:
        contract = json.loads(
            (Path(run_dir) / ".pipeline" / "arch_contract.json").read_text(
                encoding="utf-8"
            )
        )
    except (OSError, json.JSONDecodeError) as exc:
        raise TrainingHistoryCoverageError(
            "training_history_architecture_contract_unavailable",
            "the schema-2 architecture contract cannot be read at the "
            f"post-smoke history boundary: {exc}",
        ) from exc
    loop = contract.get("training_loop") if isinstance(contract, Mapping) else None
    function_name = loop.get("function_name") if isinstance(loop, Mapping) else None
    if not isinstance(function_name, str) or not function_name \
            or function_name != function_name.strip():
        raise TrainingHistoryProducerError(
            "training_history_required_training_loop_missing",
            "training_history_execution requires a schema-2 training_loop "
            "with one exact function_name",
        )
    if function_name != training_callable:
        raise TrainingHistoryProducerError(
            "training_history_training_callable_disagreement",
            "schema-2 training_loop.function_name disagrees with the declared "
            f"{training_module}.{training_callable} fitting entry",
        )
    return {
        "training_module": training_module,
        "training_callable": training_callable,
    }


def _stitched_module(code_cells: Sequence[str]) -> ast.Module:
    source = "\n".join(
        "\n".join(
            line for line in str(cell).splitlines()
            if not line.lstrip().startswith(("%", "!"))
        )
        for cell in code_cells
    )
    try:
        return ast.parse(source)
    except SyntaxError as exc:
        raise TrainingHistoryCoverageError(
            "training_history_notebook_grammar_unsupported",
            f"the stitched notebook cannot be parsed for bounded value flow: {exc}",
        ) from exc


def _call_leaf(call: ast.Call) -> str:
    if isinstance(call.func, ast.Name):
        return call.func.id
    if isinstance(call.func, ast.Attribute):
        return call.func.attr
    return ""


def _expression_path(node: ast.AST) -> tuple[str, ...]:
    if isinstance(node, ast.Name):
        return (node.id,)
    if isinstance(node, ast.Attribute):
        prefix = _expression_path(node.value)
        return (*prefix, node.attr) if prefix else ()
    return ()


def _import_bound_names(node: ast.Import | ast.ImportFrom) -> set[str]:
    names: set[str] = set()
    if isinstance(node, ast.Import):
        for alias in node.names:
            names.add(alias.asname or alias.name.split(".", 1)[0])
    else:
        for alias in node.names:
            if alias.name != "*":
                names.add(alias.asname or alias.name)
    return names


def _declared_import_routes(
    tree: ast.Module,
    module_name: str,
    callable_name: str,
) -> list[dict[str, object]]:
    """Return direct top-level bindings that prove the declared import."""
    routes: list[dict[str, object]] = []
    module_parts = tuple(module_name.split("."))
    for statement in tree.body:
        if isinstance(statement, ast.ImportFrom) \
                and statement.level == 0 \
                and statement.module == module_name:
            for alias in statement.names:
                if alias.name == callable_name:
                    local = alias.asname or callable_name
                    routes.append({
                        "node": statement,
                        "call_path": (local,),
                        "binding_names": {local},
                    })
        elif isinstance(statement, ast.Import):
            for alias in statement.names:
                if alias.name != module_name:
                    continue
                if alias.asname:
                    call_path = (alias.asname, callable_name)
                    binding_names = {alias.asname}
                else:
                    call_path = (*module_parts, callable_name)
                    binding_names = {module_parts[0]}
                routes.append({
                    "node": statement,
                    "call_path": call_path,
                    "binding_names": binding_names,
                })
        elif isinstance(statement, ast.ImportFrom) \
                and statement.level == 0 \
                and statement.module == ".".join(module_parts[:-1]):
            for alias in statement.names:
                if alias.name == module_parts[-1]:
                    local = alias.asname or module_parts[-1]
                    routes.append({
                        "node": statement,
                        "call_path": (local, callable_name),
                        "binding_names": {local},
                    })
    return routes


def _validate_declared_import_route(
    tree: ast.Module,
    module_name: str,
    callable_name: str,
) -> dict[str, object]:
    routes = _declared_import_routes(tree, module_name, callable_name)
    if not routes:
        raise TrainingHistoryProducerError(
            "training_history_notebook_training_route_disagreement",
            "notebook does not import the declared fitting entry from "
            f"{module_name}.{callable_name}",
        )
    if len(routes) != 1:
        raise TrainingHistoryCoverageError(
            "training_history_notebook_import_grammar_unsupported",
            "version one proves one direct top-level binding for the declared "
            "fitting entry",
        )
    route = routes[0]
    route_node = route["node"]
    binding_names = route["binding_names"]
    assert isinstance(route_node, (ast.Import, ast.ImportFrom))
    assert isinstance(binding_names, set)

    for node in ast.walk(tree):
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            if node is not route_node \
                    and _import_bound_names(node) & binding_names:
                raise TrainingHistoryProducerError(
                    "training_history_notebook_training_binding_rebound",
                    "the declared fitting module/callable binding is replaced "
                    "by another import",
                )
        elif isinstance(node, ast.Name) \
                and isinstance(node.ctx, (ast.Store, ast.Del)) \
                and node.id in binding_names:
            raise TrainingHistoryProducerError(
                "training_history_notebook_training_binding_rebound",
                "the declared fitting module/callable binding is rebound in "
                "notebook code",
            )
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) \
                and node.name in binding_names:
            raise TrainingHistoryProducerError(
                "training_history_notebook_training_binding_rebound",
                "a local definition shadows the declared fitting binding",
            )
        elif isinstance(node, ast.arg) and node.arg in binding_names:
            raise TrainingHistoryProducerError(
                "training_history_notebook_training_binding_rebound",
                "a function argument shadows the declared fitting binding",
            )
        elif isinstance(node, ast.ExceptHandler) \
                and node.name in binding_names:
            raise TrainingHistoryProducerError(
                "training_history_notebook_training_binding_rebound",
                "an exception binding shadows the declared fitting binding",
            )
        elif isinstance(node, (ast.Attribute, ast.Subscript)) \
                and isinstance(node.ctx, (ast.Store, ast.Del)) \
                and any(
                    isinstance(child, ast.Name) and child.id in binding_names
                    for child in ast.walk(node.value)
                ):
            raise TrainingHistoryProducerError(
                "training_history_notebook_training_binding_rebound",
                "the declared fitting module binding is mutated in notebook code",
            )
    return route


def _validate_runtime_output_bindings(tree: ast.Module) -> None:
    """Bind canonical serialization to stdlib json and the built-in print."""
    json_imports: list[ast.Import] = []
    for statement in tree.body:
        if not isinstance(statement, ast.Import):
            continue
        if any(alias.name == "json" and alias.asname is None
               for alias in statement.names):
            json_imports.append(statement)
    if len(json_imports) != 1:
        raise TrainingHistoryProducerError(
            "training_history_notebook_serializer_binding_disagreement",
            "the canonical marker requires one top-level `import json` "
            "binding to the standard-library serializer",
        )
    allowed_json_import = json_imports[0]

    protected = {"json", "print"}
    for node in ast.walk(tree):
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            rebound = _import_bound_names(node) & protected
            if node is allowed_json_import:
                rebound.discard("json")
            if rebound:
                raise TrainingHistoryProducerError(
                    "training_history_notebook_output_binding_rebound",
                    "the stdlib json or built-in print binding is replaced by "
                    "another import",
                )
        elif isinstance(node, ast.Name) \
                and isinstance(node.ctx, (ast.Store, ast.Del)) \
                and node.id in protected:
            raise TrainingHistoryProducerError(
                "training_history_notebook_output_binding_rebound",
                f"output binding {node.id!r} is rebound in notebook code",
            )
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) \
                and node.name in protected:
            raise TrainingHistoryProducerError(
                "training_history_notebook_output_binding_rebound",
                f"a local definition shadows output binding {node.name!r}",
            )
        elif isinstance(node, ast.arg) and node.arg in protected:
            raise TrainingHistoryProducerError(
                "training_history_notebook_output_binding_rebound",
                f"a function argument shadows output binding {node.arg!r}",
            )
        elif isinstance(node, ast.ExceptHandler) and node.name in protected:
            raise TrainingHistoryProducerError(
                "training_history_notebook_output_binding_rebound",
                f"an exception binding shadows output binding {node.name!r}",
            )
        elif isinstance(node, (ast.Attribute, ast.Subscript)) \
                and isinstance(node.ctx, (ast.Store, ast.Del)) \
                and any(
                    isinstance(child, ast.Name) and child.id == "json"
                    for child in ast.walk(node.value)
                ):
            raise TrainingHistoryProducerError(
                "training_history_notebook_output_binding_rebound",
                "the standard-library json binding is mutated in notebook code",
            )


_DYNAMIC_NAMESPACE_CALLS = {"eval", "exec", "globals", "locals", "vars"}


def _direct_namespace_store_key(node: ast.AST) -> str | None:
    if not isinstance(node, ast.Subscript) \
            or not isinstance(node.ctx, (ast.Store, ast.Del)) \
            or not isinstance(node.value, ast.Call) \
            or _call_leaf(node.value) not in {"globals", "locals", "vars"}:
        return None
    value = _literal(node.slice)
    return value if isinstance(value, str) else ""


def _validate_protected_binding_usage(
    tree: ast.Module,
    route: Mapping[str, object],
) -> None:
    """Allow only direct invocation of the three trusted runtime bindings."""
    binding_names = route.get("binding_names")
    call_path = route.get("call_path")
    assert isinstance(binding_names, set)
    assert isinstance(call_path, tuple)
    protected = {*binding_names, "json", "print"}

    # Literal writes through a dynamic namespace are direct disagreements.
    # Unknown namespace operations remain coverage: evaluating their effects
    # would require executing notebook code, which this bounded gate forbids.
    for node in ast.walk(tree):
        key = _direct_namespace_store_key(node)
        if key is None:
            continue
        if key in protected:
            raise TrainingHistoryProducerError(
                "training_history_notebook_protected_binding_rebound",
                f"dynamic namespace mutation replaces protected binding {key!r}",
            )
        raise TrainingHistoryCoverageError(
            "training_history_notebook_dynamic_namespace_unsupported",
            "dynamic namespace mutation is outside the bounded source grammar",
        )

    # Assigning a trusted callable/module to another carrier creates an alias
    # whose later mutation or invocation cannot be proved by the direct route.
    for node in ast.walk(tree):
        if not isinstance(node, (ast.Assign, ast.AnnAssign, ast.NamedExpr)):
            continue
        value = node.value
        if not _references_names(value, protected):
            continue
        if isinstance(value, ast.Call):
            invoked = _expression_path(value.func)
            if invoked == call_path \
                    or invoked == ("print",) \
                    or invoked[:1] == ("json",):
                continue
        raise TrainingHistoryCoverageError(
            "training_history_notebook_binding_alias_unsupported",
            "a protected training/json/print binding escapes through an "
            "assignment or container outside the exact invocation route",
        )

    for node in ast.walk(tree):
        expressions: list[ast.AST] = []
        if isinstance(node, (ast.For, ast.AsyncFor)):
            expressions = [node.iter]
        elif isinstance(node, (ast.With, ast.AsyncWith)):
            expressions = [item.context_expr for item in node.items]
        elif isinstance(node, ast.Match):
            expressions = [node.subject]
        elif isinstance(node, ast.comprehension):
            expressions = [node.iter, *node.ifs]
        if any(_references_names(expression, protected)
               for expression in expressions):
            raise TrainingHistoryCoverageError(
                "training_history_notebook_binding_alias_unsupported",
                "a protected training/json/print binding crosses unsupported "
                "control-flow alias grammar",
            )

    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        leaf = _call_leaf(node)
        if leaf in _DYNAMIC_NAMESPACE_CALLS:
            raise TrainingHistoryCoverageError(
                "training_history_notebook_dynamic_namespace_unsupported",
                f"dynamic namespace operation {leaf}(...) is outside the "
                "bounded source grammar",
            )
        receiver_uses_protected = isinstance(node.func, ast.Attribute) \
            and _references_names(node.func.value, protected)
        if receiver_uses_protected and node.func.attr in _MUTATING_METHODS:
            raise TrainingHistoryProducerError(
                "training_history_notebook_protected_binding_mutated",
                "a protected training/json/print binding is mutated through "
                f"{node.func.attr}(...) ",
            )
        argument_uses_protected = any(
            _references_names(argument, protected) for argument in node.args
        ) or any(
            _references_names(keyword.value, protected)
            for keyword in node.keywords
        )
        if _expression_path(node.func) == ("print",) \
                and _contains_marker(node, _assignments(tree)) \
                and not any(
                    _references_names(argument, {*binding_names, "print"})
                    for argument in node.args
                ):
            # The sole canonical marker is allowed to contain json.dumps;
            # exact serializer and direct-statement checks run below.
            argument_uses_protected = False
        if leaf in {"setattr", "delattr"} and argument_uses_protected:
            raise TrainingHistoryProducerError(
                "training_history_notebook_protected_binding_mutated",
                "setattr/delattr mutates a protected training/json/print binding",
            )
        if argument_uses_protected:
            raise TrainingHistoryCoverageError(
                "training_history_notebook_binding_alias_unsupported",
                "a protected training/json/print binding is passed to another "
                "call outside the exact invocation route",
            )


def _parents(tree: ast.AST) -> dict[ast.AST, ast.AST]:
    result: dict[ast.AST, ast.AST] = {}
    for parent in ast.walk(tree):
        for child in ast.iter_child_nodes(parent):
            result[child] = parent
    return result


_SCOPES = (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef, ast.Lambda)


def _inside_nested_scope(
    node: ast.AST,
    parents: Mapping[ast.AST, ast.AST],
) -> bool:
    current = parents.get(node)
    while current is not None:
        if isinstance(current, _SCOPES):
            return True
        current = parents.get(current)
    return False


def _assignments(tree: ast.Module) -> dict[str, list[ast.AST]]:
    result: dict[str, list[ast.AST]] = {}
    for statement in tree.body:
        target: ast.AST | None = None
        value: ast.AST | None = None
        if isinstance(statement, ast.Assign) and len(statement.targets) == 1:
            target, value = statement.targets[0], statement.value
        elif isinstance(statement, ast.AnnAssign):
            target, value = statement.target, statement.value
        if isinstance(target, ast.Name) and value is not None:
            result.setdefault(target.id, []).append(value)
    return result


def _assignment_pairs(tree: ast.Module) -> list[tuple[ast.Name, ast.AST]]:
    """All simple bindings, including nested/conditional shadow writes."""
    result: list[tuple[ast.Name, ast.AST]] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    result.append((target, node.value))
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name) \
                and node.value is not None:
            result.append((node.target, node.value))
        elif isinstance(node, ast.NamedExpr) and isinstance(node.target, ast.Name):
            result.append((node.target, node.value))
    return result


def _resolve_name(
    expression: ast.AST,
    assignments: Mapping[str, list[ast.AST]],
    *,
    seen: frozenset[str] = frozenset(),
) -> ast.AST:
    if not isinstance(expression, ast.Name):
        return expression
    definitions = assignments.get(expression.id)
    if definitions is None:
        return expression
    if len(definitions) != 1 or expression.id in seen:
        raise TrainingHistoryCoverageError(
            "training_history_notebook_alias_unsupported",
            f"notebook value {expression.id!r} has ambiguous or cyclic "
            "assignments outside the bounded direct grammar",
        )
    return _resolve_name(
        definitions[0], assignments, seen=seen | {expression.id}
    )


def _resolved_nodes(
    expression: ast.AST,
    assignments: Mapping[str, list[ast.AST]],
    *,
    seen: frozenset[str] = frozenset(),
):
    if isinstance(expression, ast.Name) and expression.id in assignments:
        if expression.id in seen:
            raise TrainingHistoryCoverageError(
                "training_history_notebook_alias_unsupported",
                f"notebook value {expression.id!r} forms a cyclic alias",
            )
        definitions = assignments[expression.id]
        if len(definitions) != 1:
            raise TrainingHistoryCoverageError(
                "training_history_notebook_alias_unsupported",
                f"notebook value {expression.id!r} has multiple assignments",
            )
        yield from _resolved_nodes(
            definitions[0], assignments, seen=seen | {expression.id}
        )
        return
    yield expression
    for child in ast.iter_child_nodes(expression):
        yield from _resolved_nodes(child, assignments, seen=seen)


def _resolution_names(
    expression: ast.AST,
    assignments: Mapping[str, list[ast.AST]],
    *,
    seen: frozenset[str] = frozenset(),
) -> set[str]:
    names: set[str] = set()
    if isinstance(expression, ast.Name) and expression.id in assignments:
        names.add(expression.id)
        if expression.id in seen:
            return names
        definitions = assignments[expression.id]
        if len(definitions) == 1:
            names.update(_resolution_names(
                definitions[0], assignments, seen=seen | {expression.id}
            ))
        return names
    # Follow only identity-preserving carriers.  Do not descend into the
    # fitting call's arguments: model/data inputs are not aliases of its
    # returned mapping.
    if isinstance(expression, (ast.Subscript, ast.Attribute)):
        names.update(_resolution_names(expression.value, assignments, seen=seen))
    return names


def _references_names(expression: ast.AST, names: set[str]) -> bool:
    return any(
        isinstance(node, ast.Name) and node.id in names
        for node in ast.walk(expression)
    )


_MUTATING_METHODS = {
    "__delitem__",
    "__setitem__",
    "add",
    "append",
    "clear",
    "discard",
    "extend",
    "insert",
    "pop",
    "popitem",
    "remove",
    "reverse",
    "setdefault",
    "sort",
    "update",
}


def _validate_alias_integrity(
    tree: ast.Module,
    assignments: Mapping[str, list[ast.AST]],
    *,
    raw_payload: ast.AST,
    training_call: ast.Call,
    result_binding: ast.Name,
    history_key: str,
    allowed_calls: set[ast.Call],
) -> None:
    """Reject any write that can alter the exact value reaching the marker."""
    protected = _resolution_names(raw_payload, assignments)
    protected.add(result_binding.id)
    pairs = _assignment_pairs(tree)

    # Close over aliases created anywhere in the notebook.  A conditional or
    # nested alias is not part of the accepted direct grammar, but it must not
    # provide an unobserved mutation path to the result/history objects.
    changed = True
    while changed:
        changed = False
        for target, value in pairs:
            if target.id in protected:
                continue
            aliases_protected = isinstance(value, ast.Name) \
                and value.id in protected
            resolved = value
            try:
                resolved = _resolve_name(value, assignments)
            except TrainingHistoryCoverageError:
                pass
            if isinstance(resolved, ast.Subscript) \
                    and _subscript_key(resolved) == history_key:
                try:
                    aliases_protected = aliases_protected or (
                        _resolve_name(resolved.value, assignments)
                        is training_call
                    )
                except TrainingHistoryCoverageError:
                    pass
            if aliases_protected:
                protected.add(target.id)
                changed = True

    allowed_targets = {
        target
        for target, _ in pairs
        if target.id in protected
        and any(
            target is candidate
            for statement in tree.body
            for candidate in (
                list(statement.targets)
                if isinstance(statement, ast.Assign) else
                [statement.target]
                if isinstance(statement, ast.AnnAssign) else []
            )
        )
    }
    # Every protected binding must have one unambiguous top-level definition.
    for name in protected:
        definitions = assignments.get(name)
        if definitions is None or len(definitions) != 1:
            raise TrainingHistoryProducerError(
                "training_history_notebook_result_alias_rebound",
                f"result/history alias {name!r} is not bound exactly once at "
                "top level",
            )

    # A container/attribute/subscript that captures either protected object is
    # an alias escape.  Version one cannot prove what later operations on that
    # carrier mutate, so it must never silently pass as a direct flow.
    for node in ast.walk(tree):
        if not isinstance(node, (ast.Assign, ast.AnnAssign, ast.NamedExpr)):
            continue
        value = node.value
        if not _references_names(value, protected):
            continue
        direct_alias = isinstance(value, ast.Name) and value.id in protected
        resolved = value
        try:
            resolved = _resolve_name(value, assignments)
        except TrainingHistoryCoverageError:
            pass
        if isinstance(resolved, ast.Subscript) \
                and _subscript_key(resolved) == history_key:
            try:
                direct_alias = direct_alias or (
                    _resolve_name(resolved.value, assignments) is training_call
                )
            except TrainingHistoryCoverageError:
                pass
        targets = (
            node.targets if isinstance(node, ast.Assign) else [node.target]
        )
        if any(
            isinstance(target, (ast.Attribute, ast.Subscript))
            and _references_names(target.value, protected)
            for target in targets
        ):
            # This is a direct mutation, classified producer-owned in the
            # store scan below rather than as an unsupported alias escape.
            continue
        if direct_alias and len(targets) == 1 \
                and isinstance(targets[0], ast.Name) \
                and targets[0].id in protected:
            continue
        raise TrainingHistoryCoverageError(
            "training_history_notebook_alias_escape_unsupported",
            "the fitting result or history escapes through a container, "
            "attribute, or subscript outside the bounded direct grammar",
        )

    for node in ast.walk(tree):
        expressions: list[ast.AST] = []
        if isinstance(node, (ast.For, ast.AsyncFor)):
            expressions = [node.iter]
        elif isinstance(node, (ast.With, ast.AsyncWith)):
            expressions = [item.context_expr for item in node.items]
        elif isinstance(node, ast.Match):
            expressions = [node.subject]
        elif isinstance(node, ast.comprehension):
            expressions = [node.iter, *node.ifs]
        if any(_references_names(expression, protected)
               for expression in expressions):
            raise TrainingHistoryCoverageError(
                "training_history_notebook_alias_escape_unsupported",
                "the fitting result or history crosses unsupported for/with/"
                "match/comprehension alias grammar",
            )

    for node in ast.walk(tree):
        if isinstance(node, ast.Name) \
                and isinstance(node.ctx, (ast.Store, ast.Del)) \
                and node.id in protected \
                and node not in allowed_targets:
            raise TrainingHistoryProducerError(
                "training_history_notebook_result_alias_rebound",
                f"result/history alias {node.id!r} is rebound outside its "
                "single direct assignment",
            )
        if isinstance(node, (ast.Attribute, ast.Subscript)) \
                and isinstance(node.ctx, (ast.Store, ast.Del)) \
                and _references_names(node.value, protected):
            raise TrainingHistoryProducerError(
                "training_history_notebook_history_mutated",
                "the fitting result or training-history value is mutated "
                "before the canonical marker is emitted",
            )
        if not isinstance(node, ast.Call) or node in allowed_calls:
            continue
        receiver_uses_protected = isinstance(node.func, ast.Attribute) \
            and _references_names(node.func.value, protected)
        argument_uses_protected = any(
            _references_names(argument, protected) for argument in node.args
        ) or any(
            _references_names(keyword.value, protected)
            for keyword in node.keywords
        )
        if _call_leaf(node) in {"setattr", "delattr"} \
                and argument_uses_protected:
            raise TrainingHistoryProducerError(
                "training_history_notebook_history_mutated",
                "setattr/delattr mutates the fitting result or training-history "
                "value before output",
            )
        if receiver_uses_protected and node.func.attr in _MUTATING_METHODS:
            raise TrainingHistoryProducerError(
                "training_history_notebook_history_mutated",
                "the fitting result or training-history value is passed "
                f"through mutating method {node.func.attr}(...) before output",
            )
        if receiver_uses_protected or argument_uses_protected:
            raise TrainingHistoryCoverageError(
                "training_history_notebook_alias_grammar_unsupported",
                "the fitting result or history crosses an additional call "
                "whose mutation behavior is outside the bounded direct grammar",
            )


def _contains_marker(
    print_call: ast.Call,
    assignments: Mapping[str, list[ast.AST]],
) -> bool:
    try:
        nodes = [
            node
            for argument in print_call.args
            for node in _resolved_nodes(argument, assignments)
        ]
    except TrainingHistoryCoverageError:
        nodes = [node for argument in print_call.args for node in ast.walk(argument)]
    return any(
        (
            isinstance(node, ast.Constant)
            and isinstance(node.value, str)
            and TRAINING_HISTORY_MARKER in node.value
        )
        or (
            isinstance(node, ast.Name)
            and node.id == "TRAINING_HISTORY_MARKER"
        )
        for node in nodes
    )


def _is_json_dumps(call: ast.Call) -> bool:
    return (
        isinstance(call.func, ast.Attribute)
        and isinstance(call.func.value, ast.Name)
        and call.func.value.id == "json"
        and call.func.attr == "dumps"
    )


def _literal(node: ast.AST) -> object:
    try:
        return ast.literal_eval(node)
    except (ValueError, TypeError, SyntaxError):
        return object()


def _validate_canonical_dumps(call: ast.Call) -> ast.AST:
    if len(call.args) != 1 or any(keyword.arg is None for keyword in call.keywords):
        raise TrainingHistoryProducerError(
            "training_history_notebook_serializer_disagreement",
            "the marker must serialize exactly one training-history value",
        )
    keywords = {keyword.arg: keyword.value for keyword in call.keywords}
    expected = {
        "sort_keys": True,
        "separators": (",", ":"),
        "ensure_ascii": False,
        "allow_nan": False,
    }
    if set(keywords) != set(expected) or any(
        _literal(keywords[name]) != value for name, value in expected.items()
    ):
        raise TrainingHistoryProducerError(
            "training_history_notebook_serializer_disagreement",
            "the marker must use json.dumps with sort_keys=True, "
            "separators=(',', ':'), ensure_ascii=False, and allow_nan=False",
        )
    return call.args[0]


def _subscript_key(node: ast.Subscript) -> object:
    return _literal(node.slice)


def validate_training_history_notebook_flow(
    code_cells: Sequence[str],
    build_plan: Mapping[str, object],
) -> dict[str, str]:
    """Prove the bounded fitting-result -> marker value flow or raise typed."""
    training_module, training_callable, history_key = _flow_contract(build_plan)
    tree = _stitched_module(code_cells)
    parents = _parents(tree)
    assignments = _assignments(tree)
    _validate_runtime_output_bindings(tree)
    route = _validate_declared_import_route(
        tree, training_module, training_callable
    )
    _validate_protected_binding_usage(tree, route)
    call_path = route["call_path"]
    assert isinstance(call_path, tuple)

    leaf_training_calls = [
        node for node in ast.walk(tree)
        if isinstance(node, ast.Call) and _call_leaf(node) == training_callable
    ]
    all_training_calls = [
        node for node in leaf_training_calls
        if _expression_path(node.func) == call_path
    ]
    if len(all_training_calls) != len(leaf_training_calls):
        raise TrainingHistoryProducerError(
            "training_history_notebook_training_route_disagreement",
            "a fitting call with the declared callable name does not resolve "
            f"through the exact {training_module} import binding",
        )
    top_training_calls = [
        node for node in all_training_calls
        if not _inside_nested_scope(node, parents)
    ]
    if not all_training_calls:
        raise TrainingHistoryProducerError(
            "training_history_notebook_training_call_missing",
            f"notebook does not call the declared fitting entry "
            f"{training_callable}(...) before emitting training history",
        )
    if len(all_training_calls) != 1 or len(top_training_calls) != 1:
        raise TrainingHistoryCoverageError(
            "training_history_notebook_training_grammar_unsupported",
            "version one proves one top-level fitting call only; helper-owned "
            "or multiple training calls require a wider grammar",
        )
    training_call = top_training_calls[0]
    parent = parents.get(training_call)
    if isinstance(parent, ast.Expr):
        raise TrainingHistoryProducerError(
            "training_history_notebook_training_result_discarded",
            "the declared fitting call result is discarded, so its exact "
            "training_history mapping value cannot reach the marker",
        )
    result_binding: ast.Name | None = None
    result_statement: ast.AST | None = None
    if isinstance(parent, ast.Assign) and parent.value is training_call:
        result_statement = parent
        if len(parent.targets) == 1 and isinstance(parent.targets[0], ast.Name):
            result_binding = parent.targets[0]
    elif isinstance(parent, ast.AnnAssign) and parent.value is training_call:
        result_statement = parent
        if isinstance(parent.target, ast.Name):
            result_binding = parent.target
    if result_binding is None:
        raise TrainingHistoryProducerError(
            "training_history_notebook_training_result_binding_disagreement",
            "the declared fitting call returns one mapping and must be assigned "
            "to one name before reading its exact training_history key",
        )
    if result_statement not in tree.body:
        raise TrainingHistoryCoverageError(
            "training_history_notebook_training_grammar_unsupported",
            "the fitting call is conditional or nested; version one proves "
            "one direct top-level result assignment only",
        )

    leaf_prints = [
        node for node in ast.walk(tree)
        if isinstance(node, ast.Call) and _call_leaf(node) == "print"
    ]
    all_prints = [
        node for node in leaf_prints
        if _expression_path(node.func) == ("print",)
    ]
    wrong_prints = [
        call for call in leaf_prints
        if call not in all_prints and _contains_marker(call, assignments)
    ]
    if wrong_prints:
        raise TrainingHistoryProducerError(
            "training_history_notebook_print_route_disagreement",
            "the canonical marker is not emitted through the exact built-in "
            "print binding",
        )
    marker_prints = [
        call for call in all_prints if _contains_marker(call, assignments)
    ]
    if not marker_prints:
        raise TrainingHistoryProducerError(
            "training_history_notebook_marker_source_missing",
            "notebook source has no print of the canonical training-history marker",
        )
    if len(marker_prints) != 1:
        raise TrainingHistoryProducerError(
            "training_history_notebook_marker_source_ambiguous",
            f"notebook source has {len(marker_prints)} training-history marker prints",
        )
    marker_print = marker_prints[0]
    if _inside_nested_scope(marker_print, parents):
        raise TrainingHistoryCoverageError(
            "training_history_notebook_marker_grammar_unsupported",
            "the marker is emitted through a helper/function body; version one "
            "proves only direct top-level serialization",
        )
    marker_statement = parents.get(marker_print)
    if not isinstance(marker_statement, ast.Expr) \
            or marker_statement not in tree.body:
        raise TrainingHistoryCoverageError(
            "training_history_notebook_marker_grammar_unsupported",
            "the canonical marker print must be one direct top-level statement; "
            "conditional/loop/try/with emission is outside version one",
        )

    resolved_print_nodes = [
        node
        for argument in marker_print.args
        for node in _resolved_nodes(argument, assignments)
    ]
    serializers = [
        node for node in resolved_print_nodes
        if isinstance(node, ast.Call) and _is_json_dumps(node)
    ]
    if not serializers:
        other_calls = [
            node for node in resolved_print_nodes
            if isinstance(node, ast.Call)
        ]
        if other_calls:
            raise TrainingHistoryCoverageError(
                "training_history_notebook_marker_grammar_unsupported",
                "the marker payload flows through an unsupported serializer/helper",
            )
        raise TrainingHistoryProducerError(
            "training_history_notebook_marker_literal",
            "the marker payload is independent literal data rather than the "
            "declared fitting result's training_history value",
        )
    if len(serializers) != 1:
        raise TrainingHistoryProducerError(
            "training_history_notebook_marker_source_ambiguous",
            "the marker print contains multiple JSON payload serializers",
        )

    raw_payload = _validate_canonical_dumps(serializers[0])
    payload = _resolve_name(raw_payload, assignments)
    if not isinstance(payload, ast.Subscript):
        if isinstance(payload, (ast.Call, ast.Name)):
            raise TrainingHistoryCoverageError(
                "training_history_notebook_history_grammar_unsupported",
                "the serialized history flows through an unsupported helper or "
                "control-flow carrier",
            )
        raise TrainingHistoryProducerError(
            "training_history_notebook_marker_literal",
            "the serialized marker payload is not read from the fitting result",
        )
    actual_key = _subscript_key(payload)
    if actual_key != history_key:
        raise TrainingHistoryProducerError(
            "training_history_notebook_result_key_disagreement",
            f"marker reads fitting result key {actual_key!r}; the declared exact "
            f"key is {history_key!r}",
        )
    carrier = _resolve_name(payload.value, assignments)
    if carrier is not training_call:
        if isinstance(carrier, ast.Call):
            raise TrainingHistoryCoverageError(
                "training_history_notebook_history_grammar_unsupported",
                "the history carrier comes from an unsupported helper call",
            )
        raise TrainingHistoryProducerError(
            "training_history_notebook_result_disconnected",
            "the exact training_history key is not read from the declared "
            "fitting call result",
        )
    _validate_alias_integrity(
        tree,
        assignments,
        raw_payload=raw_payload,
        training_call=training_call,
        result_binding=result_binding,
        history_key=history_key,
        allowed_calls={serializers[0], marker_print},
    )
    return {
        "training_module": training_module,
        "training_callable": training_callable,
        "history_key": history_key,
        "marker": TRAINING_HISTORY_MARKER,
    }


__all__ = [
    "TRAINING_HISTORY_MARKER",
    "training_history_notebook_applicable",
    "validate_training_history_architecture_contract",
    "validate_training_history_notebook_flow",
]
