#!/usr/bin/env python3
"""Repo-hygiene check. The driver never calls this.

Advisory readiness checks for taxonomy-served paradigm packs.

The filename is retained for the standing verification gate. The legacy
``paradigms/**/FIELD_GUIDE.md`` chain was retired in Phase 4; this script now
checks the SSOT pack/build-plan surface that replaced it.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from scripts import taxonomy, taxonomy_role_views  # noqa: E402
from scripts.build_plan import load_build_plan  # noqa: E402


READINESS_DOC = Path("docs/generated/field-guide-readiness.md")
ROLE_OUTPUT_ROOT = taxonomy_role_views.ROLE_OUTPUT_ROOT
REPORT_MARKER = "<!-- Generated by scripts/validate_field_guides.py report. -->"
KNOWN_ROUTE_TARGETS = {
    "human",
    "r2c-architecture-coder",
    "r2c-method-coder",
    "r2c-notebook-generator",
    "r2c-stage-reviewer",
    "r2c-smoke-diagnostician",
}


@dataclass(frozen=True)
class CoverageRow:
    consumer: str
    field: str
    status: str
    detail: str

    def as_dict(self) -> dict[str, str]:
        return {
            "consumer": self.consumer,
            "field": self.field,
            "status": self.status,
            "detail": self.detail,
        }


@dataclass(frozen=True)
class TaxonomyReadinessDiagnostic:
    severity: str
    code: str
    message: str
    paradigm: str | None = None

    def as_dict(self) -> dict[str, Any]:
        payload: dict[str, Any] = {
            "severity": self.severity,
            "code": self.code,
            "message": self.message,
        }
        if self.paradigm:
            payload["paradigm"] = self.paradigm
        return payload


@dataclass(frozen=True)
class GeneratedDocMismatch:
    path: str
    issue: str
    diff: str = ""


def build_readiness(repo_root: Path = ROOT) -> dict[str, Any]:
    tax = taxonomy.load_taxonomy(repo_root)
    diagnostics: list[TaxonomyReadinessDiagnostic] = []
    node_rows: list[dict[str, Any]] = []

    for paradigm_id in sorted(tax._node_by_legacy):
        pack = taxonomy.load_pack(paradigm_id, repo_root)
        if pack is None:
            node_diagnostics = [
                TaxonomyReadinessDiagnostic(
                    "error",
                    "taxonomy_pack_missing",
                    "legacy paradigm id is registered but not taxonomy-served",
                    paradigm_id,
                )
            ]
            coverage: list[CoverageRow] = []
            taxonomy_id = "-"
        else:
            taxonomy_id = str(pack.get("taxonomy_id") or "-")
            plan = load_build_plan(_build_doc_spec(paradigm_id, pack), repo_root)
            coverage, node_diagnostics = _coverage_for_pack(paradigm_id, pack, plan, repo_root)

        diagnostics.extend(node_diagnostics)
        node_rows.append(
            {
                "paradigm": paradigm_id,
                "taxonomy_id": taxonomy_id,
                "status": _status_for(paradigm_id, diagnostics),
                "coverage": [row.as_dict() for row in coverage],
                "diagnostics": [
                    d.as_dict()
                    for d in diagnostics
                    if d.paradigm == paradigm_id
                ],
            }
        )

    error_count = sum(1 for d in diagnostics if d.severity == "error")
    warning_count = sum(1 for d in diagnostics if d.severity == "warning")
    return {
        "schema_version": "2.0",
        "generated_by": "scripts/validate_field_guides.py",
        "runtime_behavior": "advisory only; runtime consumers read scripts.taxonomy and scripts.build_plan",
        "status": "failed" if error_count else ("has_warnings" if warning_count else "ready"),
        "summary": {
            "node_count": len(node_rows),
            "error_count": error_count,
            "warning_count": warning_count,
        },
        "nodes": node_rows,
        "diagnostics": [d.as_dict() for d in diagnostics],
    }


def render_readiness_report(readiness: dict[str, Any]) -> str:
    summary = readiness["summary"]
    lines: list[str] = [
        "# Taxonomy Pack Readiness",
        "",
        REPORT_MARKER,
        "",
        "> Generated from `docs/ssot/taxonomies.yaml` by `scripts/validate_field_guides.py report --write`.",
        "> This is advisory maintainer documentation only; runtime consumers use `scripts.taxonomy` and `scripts.build_plan`.",
        "",
        "## Summary",
        "",
        f"- Status: `{readiness['status']}`",
        f"- Taxonomy-served legacy nodes: {summary['node_count']}",
        f"- Errors: {summary['error_count']}",
        f"- Warnings: {summary['warning_count']}",
        "- Legacy `FIELD_GUIDE.md` files are no longer an authoring or runtime source.",
        "- Generated taxonomy role views live under `docs/generated/field-guides/` and are managed by `scripts/refresh_ssot_docs.py`.",
        "",
        "## Node Inventory",
        "",
        _table(
            ["Paradigm", "Taxonomy Node", "Status"],
            [
                [row["paradigm"], row["taxonomy_id"], row["status"]]
                for row in readiness["nodes"]
            ],
        ),
        "",
        "## Effective Consumer Coverage",
        "",
    ]

    for row in readiness["nodes"]:
        lines.extend(
            [
                f"### {row['paradigm']}",
                "",
                _table(
                    ["Consumer", "Effective Field", "Status", "Detail"],
                    [
                        [
                            coverage["consumer"],
                            coverage["field"],
                            coverage["status"],
                            coverage["detail"],
                        ]
                        for coverage in row["coverage"]
                    ],
                )
                if row["coverage"]
                else "_Coverage unavailable because the node is not taxonomy-served._",
                "",
            ]
        )

    lines.extend(["## Diagnostics", ""])
    diagnostics = readiness["diagnostics"]
    if diagnostics:
        lines.append(
            _table(
                ["Severity", "Code", "Paradigm", "Message"],
                [
                    [
                        item["severity"],
                        item["code"],
                        item.get("paradigm") or "-",
                        item["message"],
                    ]
                    for item in diagnostics
                ],
            )
        )
    else:
        lines.append("_No readiness diagnostics._")
    lines.append("")
    return "\n".join(lines)


def expected_generated_docs(
    repo_root: Path = ROOT,
    report_output: Path = READINESS_DOC,
    role_output_root: Path = ROLE_OUTPUT_ROOT,
) -> tuple[dict[Path, str], dict[str, Any]]:
    _ = role_output_root  # Role views are checked by scripts/refresh_ssot_docs.py.
    readiness = build_readiness(repo_root)
    return {report_output: render_readiness_report(readiness)}, readiness


def check_generated_docs(
    repo_root: Path = ROOT,
    report_output: Path = READINESS_DOC,
    role_output_root: Path = ROLE_OUTPUT_ROOT,
    *,
    include_diff: bool = False,
) -> tuple[list[GeneratedDocMismatch], dict[str, Any]]:
    expected, readiness = expected_generated_docs(repo_root, report_output, role_output_root)
    mismatches: list[GeneratedDocMismatch] = []

    for rel_path, expected_text in sorted(expected.items(), key=lambda item: item[0].as_posix()):
        path = repo_root / rel_path
        if not path.is_file():
            mismatches.append(GeneratedDocMismatch(rel_path.as_posix(), "missing"))
            continue
        actual_text = path.read_text(encoding="utf-8")
        if actual_text == expected_text:
            continue
        diff = ""
        if include_diff:
            diff = "".join(
                difflib.unified_diff(
                    actual_text.splitlines(keepends=True),
                    expected_text.splitlines(keepends=True),
                    fromfile=f"{rel_path.as_posix()} (current)",
                    tofile=f"{rel_path.as_posix()} (expected)",
                )
            )
        mismatches.append(GeneratedDocMismatch(rel_path.as_posix(), "stale", diff))

    return mismatches, readiness


def _coverage_for_pack(
    paradigm_id: str,
    pack: dict[str, Any],
    plan: dict[str, Any] | None,
    repo_root: Path,
) -> tuple[list[CoverageRow], list[TaxonomyReadinessDiagnostic]]:
    rows: list[CoverageRow] = []
    diagnostics: list[TaxonomyReadinessDiagnostic] = []

    def add(
        consumer: str,
        field: str,
        ok: bool,
        detail_ok: str,
        detail_fail: str,
        *,
        severity: str = "error",
        code: str,
    ) -> None:
        status = "ok" if ok else ("warning" if severity == "warning" else "missing")
        rows.append(CoverageRow(consumer, field, status, detail_ok if ok else detail_fail))
        if not ok:
            diagnostics.append(
                TaxonomyReadinessDiagnostic(severity, code, detail_fail, paradigm_id)
            )

    add(
        "analyzer",
        "classification.id",
        bool(pack.get("legacy_paradigm") == paradigm_id and pack.get("taxonomy_id")),
        "legacy id maps to taxonomy node",
        "legacy id does not map to a served taxonomy node",
        code="taxonomy_mapping_missing",
    )
    add(
        "analyzer",
        "fingerprint.positive_signals",
        bool(((pack.get("fingerprint") or {}).get("positive_signals") or [])),
        "fingerprint signals available",
        "`fingerprint.positive_signals` missing or empty",
        code="fingerprint_signals_missing",
    )
    add(
        "analyzer",
        "scaffold_hints.interface_hint",
        bool((pack.get("scaffold_hints") or {}).get("interface_hint")),
        "interface hint available",
        "`scaffold_hints.interface_hint` missing",
        code="interface_hint_missing",
    )
    templates_dir = (pack.get("scaffold_hints") or {}).get("templates_dir")
    add(
        "scaffolder",
        "scaffold_hints.templates_dir",
        isinstance(templates_dir, str) and (repo_root / templates_dir).is_dir(),
        "templates directory exists",
        "`scaffold_hints.templates_dir` missing or does not exist",
        code="templates_dir_missing",
    )
    pluggable = pack.get("pluggable_component") or {}
    add(
        "producer/validators",
        "pluggable_component.signature_template",
        bool(pluggable.get("name") and pluggable.get("signature_template") and pluggable.get("contract")),
        "pluggable name, signature, and contract available",
        "`pluggable_component` must declare name, signature_template, and contract",
        code="pluggable_component_incomplete",
    )
    seed_param = (pluggable.get("contract") or {}).get("seed_param")
    if isinstance(seed_param, str) and seed_param:
        params = _signature_param_names(str(pluggable.get("signature_template") or ""))
        add(
            "producer/validators",
            "pluggable_component.contract.seed_param",
            params is None or seed_param in params,
            "seed parameter is declared by the signature template",
            "`pluggable_component.contract.seed_param` is not present in signature_template",
            code="pluggable_seed_param_missing_from_signature",
        )

    add(
        "package validators",
        "build_plan.package_manifest.files",
        isinstance(((plan or {}).get("package_manifest") or {}).get("files"), list)
        and bool(((plan or {}).get("package_manifest") or {}).get("files")),
        "spec-derived package manifest available",
        "spec-derived build plan has no package_manifest.files",
        code="build_plan_package_manifest_missing",
    )
    add(
        "method-package validator",
        "package_manifest method/method.py public symbol",
        _plan_mentions_pluggable(plan, pluggable.get("name")),
        "method/method.py exports the pluggable function",
        "package manifest does not expose the pluggable function from method/method.py",
        code="build_plan_pluggable_symbol_missing",
    )
    add(
        "architecture validator",
        "build_plan.arch_contract_requirements.required_blocks",
        isinstance(
            (((plan or {}).get("arch_contract_requirements") or {}).get("required_blocks")),
            dict,
        )
        and bool(((plan or {}).get("arch_contract_requirements") or {}).get("required_blocks")),
        "spec-derived architecture requirements available",
        "spec-derived build plan has no arch_contract_requirements.required_blocks",
        code="build_plan_arch_contract_missing",
    )
    notebook_sections = (pack.get("notebook_layout") or {}).get("sections")
    if isinstance(notebook_sections, list) and notebook_sections:
        rows.append(
            CoverageRow(
                "notebook validator",
                "notebook_layout.sections",
                "ok",
                "notebook section contract available",
            )
        )
    else:
        rows.append(
            CoverageRow(
                "notebook validator",
                "notebook_layout.sections",
                "n/a",
                "node does not declare a notebook section contract",
            )
        )

    for stage_id in taxonomy.REVIEW_STAGE_IDS:
        stage_block = taxonomy.merged_stage_review_focus(None, paradigm_id, stage_id)
        checks = stage_block.get("semantic_checks") if isinstance(stage_block, dict) else None
        add(
            "stage reviewer",
            f"semantic_checks[{stage_id}]",
            isinstance(checks, list) and bool(checks),
            "taxonomy semantic checks available",
            f"taxonomy node has no semantic checks for {stage_id}",
            code="stage_semantic_checks_missing",
        )

    smoke_bugs = pack.get("smoke_bugs")
    if isinstance(smoke_bugs, list) and smoke_bugs:
        rows.append(
            CoverageRow(
                "smoke diagnostician",
                "smoke_bugs",
                "ok",
                "taxonomy smoke-bug catalog available",
            )
        )
    else:
        rows.append(
            CoverageRow(
                "smoke diagnostician",
                "smoke_bugs",
                "n/a",
                "node does not declare smoke-bug coverage",
            )
        )

    diagnostics.extend(_smoke_route_diagnostics(paradigm_id, pack))
    return rows, diagnostics


def _build_doc_spec(paradigm_id: str, pack: dict[str, Any]) -> dict[str, Any]:
    pluggable = pack.get("pluggable_component") or {}
    contract = pluggable.get("contract") if isinstance(pluggable.get("contract"), dict) else {}
    return {
        "comparison": {
            "classification": {"id": paradigm_id},
            "pluggable_component": {
                "name": pluggable.get("name"),
                "signature": pluggable.get("signature_template"),
                "seed_param": contract.get("seed_param") or "seed",
            },
        },
        "critical_requirements": {
            "model": {"specific_features": []},
            "required_model_methods": [],
        },
    }


def _plan_mentions_pluggable(plan: dict[str, Any] | None, name: Any) -> bool:
    if not isinstance(name, str) or not name:
        return False
    manifest = (plan or {}).get("package_manifest") or {}
    for entry in manifest.get("files") or []:
        if not isinstance(entry, dict) or entry.get("path") != "method/method.py":
            continue
        for symbol in entry.get("public_symbols") or []:
            if isinstance(symbol, dict) and symbol.get("kind") == "function" and symbol.get("name") == name:
                return True
    return False


def _signature_param_names(signature_template: str) -> list[str] | None:
    if not signature_template or "(" not in signature_template:
        return None
    try:
        tree = ast.parse(f"def {signature_template}:\n    pass\n")
    except SyntaxError:
        return None
    if not tree.body or not isinstance(tree.body[0], (ast.FunctionDef, ast.AsyncFunctionDef)):
        return None
    args = tree.body[0].args
    names = [arg.arg for arg in args.posonlyargs + args.args + args.kwonlyargs]
    if args.vararg:
        names.append(args.vararg.arg)
    if args.kwarg:
        names.append(args.kwarg.arg)
    return names


def _smoke_route_diagnostics(
    paradigm_id: str,
    pack: dict[str, Any],
) -> list[TaxonomyReadinessDiagnostic]:
    smoke_bugs = pack.get("smoke_bugs")
    if not isinstance(smoke_bugs, list):
        return []
    diagnostics: list[TaxonomyReadinessDiagnostic] = []
    for bug in smoke_bugs:
        if not isinstance(bug, dict):
            continue
        for cause in bug.get("typical_root_causes") or []:
            if not isinstance(cause, dict):
                continue
            fix = cause.get("fix")
            if not isinstance(fix, str) or not fix.strip():
                continue
            route = fix.strip().split()[0]
            if route not in KNOWN_ROUTE_TARGETS:
                diagnostics.append(
                    TaxonomyReadinessDiagnostic(
                        "error",
                        "smoke_bug_fix_target_unknown",
                        f"`smoke_bugs.{bug.get('id')}` routes fix to unknown target {route!r}",
                        paradigm_id,
                    )
                )
    return diagnostics


def _status_for(paradigm_id: str, diagnostics: list[TaxonomyReadinessDiagnostic]) -> str:
    relevant = [d for d in diagnostics if d.paradigm == paradigm_id]
    if any(d.severity == "error" for d in relevant):
        return "failed"
    if any(d.severity == "warning" for d in relevant):
        return "has_warnings"
    return "ready"


def _md(value: Any) -> str:
    text = str(value if value is not None else "")
    text = text.replace("|", "\\|")
    return text.replace("\n", "<br>")


def _table(headers: list[str], rows: list[list[Any]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(_md(cell) for cell in row) + " |")
    return "\n".join(lines)


def cmd_check(args: argparse.Namespace) -> int:
    readiness = build_readiness(args.repo_root)
    if args.json:
        print(json.dumps(readiness, indent=2, sort_keys=True))
    else:
        summary = readiness["summary"]
        if summary["error_count"]:
            print(
                f"taxonomy pack readiness FAILED: {summary['error_count']} error(s), "
                f"{summary['warning_count']} warning(s)",
                file=sys.stderr,
            )
            for item in readiness["diagnostics"]:
                if item["severity"] == "error":
                    print(f"  - {item.get('paradigm')}: {item['message']}", file=sys.stderr)
        elif summary["warning_count"]:
            print(
                f"taxonomy pack readiness OK with {summary['warning_count']} advisory warning(s)."
            )
        else:
            print("taxonomy pack readiness OK.")
    return 1 if readiness["summary"]["error_count"] else 0


def cmd_report(args: argparse.Namespace) -> int:
    readiness = build_readiness(args.repo_root)
    report = render_readiness_report(readiness)
    if args.write:
        target = args.repo_root / args.output
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(report, encoding="utf-8")
        print(f"wrote {args.output}")
    else:
        print(report)
    return 1 if readiness["summary"]["error_count"] else 0


def cmd_roles(args: argparse.Namespace) -> int:
    rendered = taxonomy_role_views.render_role_views(args.repo_root, args.output_root)
    if args.write:
        written = taxonomy_role_views.write_role_views(rendered, args.repo_root, args.output_root)
        print(f"role views OK: {len(rendered)} rendered, {written} written.")
    else:
        for rel_path, text in sorted(rendered.items(), key=lambda item: item[0].as_posix()):
            print(f"===== {rel_path.as_posix()} =====")
            print(text.rstrip())
    return 0


def cmd_generated_check(args: argparse.Namespace) -> int:
    mismatches, readiness = check_generated_docs(
        args.repo_root,
        args.output,
        args.output_root,
        include_diff=args.diff,
    )
    summary = readiness["summary"]
    if summary["error_count"]:
        print(
            f"taxonomy pack readiness FAILED: {summary['error_count']} error(s), "
            f"{summary['warning_count']} warning(s)",
            file=sys.stderr,
        )
        return 1
    if mismatches:
        print(
            f"generated taxonomy readiness docs STALE: {len(mismatches)} file(s) do not match sources.",
            file=sys.stderr,
        )
        for mismatch in mismatches:
            print(f"  - {mismatch.path}: {mismatch.issue}", file=sys.stderr)
            if mismatch.diff:
                print(mismatch.diff, file=sys.stderr)
        return 1
    print(
        "generated taxonomy readiness OK: "
        f"{args.output.as_posix()} matches sources."
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.strip())
    parser.add_argument("--repo-root", type=Path, default=ROOT)
    subparsers = parser.add_subparsers(dest="command", required=True)

    check = subparsers.add_parser("check", help="run advisory readiness checks")
    check.add_argument("--json", action="store_true", help="emit machine-readable readiness JSON")
    check.set_defaults(func=cmd_check)

    report = subparsers.add_parser("report", help="render the generated readiness report")
    report.add_argument("--write", action="store_true", help=f"write {READINESS_DOC.as_posix()}")
    report.add_argument("--output", type=Path, default=READINESS_DOC)
    report.set_defaults(func=cmd_report)

    roles = subparsers.add_parser("roles", help="render generated taxonomy role-scoped views")
    roles.add_argument("--write", action="store_true", help=f"write under {ROLE_OUTPUT_ROOT.as_posix()}")
    roles.add_argument("--output-root", type=Path, default=ROLE_OUTPUT_ROOT)
    roles.set_defaults(func=cmd_roles)

    generated_check = subparsers.add_parser(
        "generated-check",
        help="fail if generated readiness docs are stale",
    )
    generated_check.add_argument("--output", type=Path, default=READINESS_DOC)
    generated_check.add_argument("--output-root", type=Path, default=ROLE_OUTPUT_ROOT)
    generated_check.add_argument("--diff", action="store_true", help="print unified diffs for stale files")
    generated_check.set_defaults(func=cmd_generated_check)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
